repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
      - id: ruff-check
        args: [--fix, server]
      - id: ruff-format
        args: [server]

  - repo: local
    hooks:
      - id: bandit
        name: bandit
        entry: uv run --directory server --group security bandit -r . -c pyproject.toml
        language: system
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: uv run --directory server --group type mypy .
        language: system
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: uv run --directory server --group test pytest --tb=short
        language: system
        pass_filenames: false
        stages: [manual]
