"""House object item static metadata and defaults."""

from __future__ import annotations

LABEL = "house object"
TOOLTIP = "Everyday home objects that can sit on furniture, break when shoved off, and need repair, replacement, purchase, or a gift."
EDITABLE_PROPERTIES: tuple[str, ...] = (
    "title",
    "objectKind",
    "placement",
    "material",
    "fragility",
    "condition",
    "windowState",
    "ownerName",
    "keyId",
    "keyFor",
    "repairCost",
    "purchaseCost",
    "replacementHint",
    "giftable",
    "description",
    "streamUrl",
    "stationIndex",
    "stationPresets",
    "linkedMediaGroup",
    "tvChannelMode",
    "tvLibrarySources",
    "tvProviderSources",
    "mediaVolume",
    "mediaChannel",
    "mediaEffect",
    "mediaEffectValue",
    "facing",
    "enabled",
    "emitRange",
    "emitVolume",
    "emitSoundSpeed",
    "emitSoundTempo",
    "emitInitialDelay",
    "emitLoopDelay",
    "emitEffect",
    "emitEffectValue",
    "useSound",
    "emitSound",
    "phoneExtension",
    "phoneDeviceSide",
    "phoneAudioMode",
    "phoneContacts",
    "phonePbxRoutes",
)
CAPABILITIES: tuple[str, ...] = ("editable", "carryable", "deletable", "usable")
USE_SOUND: str | None = None
EMIT_SOUND: str | None = None
USE_COOLDOWN_MS = 1000
EMIT_RANGE = 10
DIRECTIONAL = False
DEFAULT_TITLE = "mug"
OBJECT_KIND_OPTIONS: tuple[str, ...] = (
    "mug",
    "cup",
    "plate",
    "bowl",
    "vase",
    "lamp",
    "book",
    "phone",
    "remote",
    "tv",
    "keys",
    "plant",
    "photo_frame",
    "candle",
    "teapot",
    "speaker",
    "radio",
    "figurine",
    "game_controller",
    "notebook",
    "clock",
    "blanket",
    "chair",
    "couch",
    "bed",
    "table",
    "counter",
    "shelf",
    "fridge",
    "sink",
    "stove",
    "oven",
    "microwave",
    "window",
    "curtain",
    "rug",
    "mailbox",
    "sign",
)
MATERIAL_OPTIONS: tuple[str, ...] = (
    "ceramic",
    "glass",
    "wood",
    "metal",
    "paper",
    "plastic",
    "fabric",
    "plant",
    "mixed",
)
FRAGILITY_OPTIONS: tuple[str, ...] = ("sturdy", "normal", "fragile", "delicate")
PLACEMENT_OPTIONS: tuple[str, ...] = (
    "floor",
    "table",
    "counter",
    "shelf",
    "wall",
    "ceiling",
    "window",
    "fixture",
    "furniture",
    "appliance",
    "carried",
)
CONDITION_OPTIONS: tuple[str, ...] = (
    "intact",
    "scuffed",
    "cracked",
    "broken",
    "repaired",
    "replacement",
)
WINDOW_STATE_OPTIONS: tuple[str, ...] = ("closed", "open")
DEFAULT_PARAMS: dict = {
    "objectKind": "mug",
    "placement": "table",
    "material": "ceramic",
    "fragility": "normal",
    "condition": "intact",
    "windowState": "closed",
    "ownerName": "",
    "keyId": "",
    "keyFor": "",
    "remoteControlLinkedRadios": True,
    "remoteControlLinkedTvs": True,
    "surfaceId": "",
    "surfaceTitle": "",
    "surfaceOrder": 0,
    "repairCost": 8,
    "purchaseCost": 14,
    "replacementHint": "A similar everyday replacement would work.",
    "giftable": True,
    "description": "A small household object.",
    "streamUrl": "",
    "playbackUrl": "",
    "stationIndex": 0,
    "stationPresets": [],
    "stationName": "",
    "nowPlaying": "",
    "stationSwitchSound": "",
    "linkedMediaGroup": "",
    "tvChannelMode": "live_and_on_demand",
    "tvLibrarySources": [],
    "tvProviderSources": [],
    "playStartedAt": 0,
    "mediaVolume": 50,
    "mediaChannel": "stereo",
    "mediaEffect": "off",
    "mediaEffectValue": 50,
    "facing": 0,
    "enabled": True,
    "emitRange": 6,
    "emitVolume": 100,
    "emitSoundSpeed": 50,
    "emitSoundTempo": 50,
    "emitInitialDelay": 0,
    "emitLoopDelay": 0,
    "emitEffect": "off",
    "emitEffectValue": 50,
    "useSound": "",
    "emitSound": "",
    "phoneExtension": "",
    "phoneDeviceSide": "",
    "phoneAudioMode": "ear_left",
    "phoneContacts": [],
    "phonePbxRoutes": [],
}
PARAM_KEYS: tuple[str, ...] = (
    "objectKind",
    "placement",
    "material",
    "fragility",
    "condition",
    "windowState",
    "ownerName",
    "keyId",
    "keyFor",
    "remoteControlLinkedRadios",
    "remoteControlLinkedTvs",
    "surfaceId",
    "surfaceTitle",
    "surfaceOrder",
    "repairCost",
    "purchaseCost",
    "replacementHint",
    "giftable",
    "description",
    "streamUrl",
    "playbackUrl",
    "stationIndex",
    "stationPresets",
    "stationName",
    "nowPlaying",
    "stationSwitchSound",
    "linkedMediaGroup",
    "tvChannelMode",
    "tvLibrarySources",
    "tvProviderSources",
    "playStartedAt",
    "mediaVolume",
    "mediaChannel",
    "mediaEffect",
    "mediaEffectValue",
    "facing",
    "enabled",
    "emitRange",
    "emitVolume",
    "emitSoundSpeed",
    "emitSoundTempo",
    "emitInitialDelay",
    "emitLoopDelay",
    "emitEffect",
    "emitEffectValue",
    "useSound",
    "emitSound",
    "phoneExtension",
    "phoneDeviceSide",
    "phoneAudioMode",
    "phoneContacts",
    "phonePbxRoutes",
)

EFFECT_OPTIONS: tuple[str, ...] = (
    "reverb",
    "echo",
    "flanger",
    "high_pass",
    "low_pass",
    "off",
)

PROPERTY_METADATA: dict[str, dict[str, object]] = {
    "stationPresets": {
        "valueType": "text",
        "label": "Station presets",
        "tooltip": "Server-managed station preset list for TV and media house objects.",
    },
    "title": {
        "valueType": "text",
        "tooltip": "Display name spoken and shown for this object.",
        "maxLength": 80,
    },
    "objectKind": {
        "valueType": "list",
        "label": "Object kind",
        "tooltip": "Kind of household object.",
        "options": list(OBJECT_KIND_OPTIONS),
    },
    "placement": {
        "valueType": "list",
        "tooltip": "Where the object belongs: floor, table, counter, wall, fixture, appliance, and similar real-world placements.",
        "options": list(PLACEMENT_OPTIONS),
    },
    "material": {
        "valueType": "list",
        "tooltip": "Primary material, used for breakage flavor.",
        "options": list(MATERIAL_OPTIONS),
    },
    "fragility": {
        "valueType": "list",
        "tooltip": "How likely this object is to break when shoved off a surface.",
        "options": list(FRAGILITY_OPTIONS),
    },
    "condition": {
        "valueType": "list",
        "tooltip": "Current repair/replacement state.",
        "options": list(CONDITION_OPTIONS),
    },
    "windowState": {
        "valueType": "list",
        "label": "Window state",
        "tooltip": "Open windows let outside ambience carry into the room; closed windows keep the room quieter.",
        "options": list(WINDOW_STATE_OPTIONS),
        "visibleWhen": {"objectKind": "window"},
    },
    "ownerName": {
        "valueType": "text",
        "label": "Owner name",
        "tooltip": "Optional owner for accountability, gifts, or replacement notes.",
        "maxLength": 80,
    },
    "keyId": {
        "valueType": "text",
        "label": "Key id",
        "tooltip": "Optional key id this object can use to unlock a matching locked door.",
        "maxLength": 80,
        "visibleWhen": {"objectKind": "keys"},
    },
    "keyFor": {
        "valueType": "text",
        "label": "Key for",
        "tooltip": "Optional spoken note for what this key opens.",
        "maxLength": 120,
        "visibleWhen": {"objectKind": "keys"},
    },
    "remoteControlLinkedRadios": {
        "valueType": "boolean",
        "label": "Control linked radios",
        "tooltip": "When on, this remote tunes connected house radios as a synced station set. When off, it controls only the nearest/current room radio.",
        "visibleWhen": {"objectKind": "remote"},
    },
    "remoteControlLinkedTvs": {
        "valueType": "boolean",
        "label": "Control linked TVs",
        "tooltip": "When on, this remote tunes connected house TVs as a synced channel set. When off, it controls only the nearest/current room TV.",
        "visibleWhen": {"objectKind": "remote"},
    },
    "repairCost": {
        "valueType": "number",
        "label": "Repair cost",
        "tooltip": "Suggested in-world repair cost.",
        "range": {"min": 0, "max": 10000, "step": 1},
    },
    "purchaseCost": {
        "valueType": "number",
        "label": "Purchase cost",
        "tooltip": "Suggested in-world replacement or purchase cost.",
        "range": {"min": 0, "max": 10000, "step": 1},
    },
    "replacementHint": {
        "valueType": "text",
        "label": "Replacement hint",
        "tooltip": "What similar object could be given or purchased.",
        "maxLength": 240,
    },
    "giftable": {
        "valueType": "boolean",
        "tooltip": "Whether another person can reasonably give a similar replacement.",
    },
    "description": {
        "valueType": "text",
        "tooltip": "Short spoken description.",
        "maxLength": 240,
    },
    "phoneExtension": {
        "valueType": "text",
        "label": "World phone extension",
        "tooltip": "Server-assigned world-only extension. Do not enter SIP credentials here.",
        "maxLength": 24,
        "visibleWhen": {"objectKind": "phone"},
    },
    "phoneDeviceSide": {
        "valueType": "list",
        "label": "Phone placement",
        "tooltip": "Where the phone appears for spatial audio: left ear, right ear, or in front as a speaker.",
        "options": ["left", "right", "front"],
        "visibleWhen": {"objectKind": "phone"},
    },
    "phoneAudioMode": {
        "valueType": "list",
        "label": "Phone audio mode",
        "tooltip": "Choose binaural ear audio, nearby speaker audio, or local-only listening.",
        "options": ["ear_left", "ear_right", "speaker", "local_only"],
        "visibleWhen": {"objectKind": "phone"},
    },
    "phoneContacts": {
        "valueType": "text",
        "label": "Phone contacts",
        "tooltip": "Saved display-only contacts; call authorization still comes from the server.",
        "visibleWhen": {"objectKind": "phone"},
    },
    "phonePbxRoutes": {
        "valueType": "text",
        "label": "Phone PBX routes",
        "tooltip": "Configured server-side PBX route labels. Credentials never belong in item data.",
        "visibleWhen": {"objectKind": "phone"},
    },
    "streamUrl": {
        "valueType": "text",
        "label": "TV stream URL",
        "tooltip": "Audio stream URL or supported station page used when this TV is on.",
        "maxLength": 2048,
        "visibleWhen": {"objectKind": "tv"},
    },
    "playbackUrl": {
        "valueType": "text",
        "label": "TV playback URL",
        "tooltip": "Server-resolved playback URL for supported TV station pages.",
        "visibleWhen": {"objectKind": "tv"},
    },
    "stationIndex": {
        "valueType": "number",
        "label": "TV channel",
        "tooltip": "Preset number. Secondary use cycles TV presets when configured.",
        "range": {"min": 0, "max": 99, "step": 1},
        "visibleWhen": {"objectKind": "tv"},
    },
    "linkedMediaGroup": {
        "valueType": "text",
        "label": "TV system",
        "tooltip": "Optional linked media group for TVs that should tune together.",
        "maxLength": 80,
        "visibleWhen": {"objectKind": "tv"},
    },
    "tvChannelMode": {
        "valueType": "list",
        "label": "TV mode",
        "tooltip": "Whether this TV exposes live generated channels, on-demand library entries, or both.",
        "options": ["live", "on_demand", "live_and_on_demand"],
        "visibleWhen": {"objectKind": "tv"},
    },
    "tvLibrarySources": {
        "valueType": "text",
        "label": "TV libraries",
        "tooltip": "Server-managed library source metadata for movies, TV shows, and misc media.",
        "visibleWhen": {"objectKind": "tv"},
    },
    "tvProviderSources": {
        "valueType": "text",
        "label": "TV providers",
        "tooltip": "Server-managed online/provider source metadata, such as Jellyfin live output or Pluto TV.",
        "visibleWhen": {"objectKind": "tv"},
    },
    "mediaVolume": {
        "valueType": "number",
        "label": "TV volume",
        "tooltip": "Playback media volume percent for this TV.",
        "range": {"min": 0, "max": 1000, "step": 1},
        "visibleWhen": {"objectKind": "tv"},
    },
    "mediaChannel": {
        "valueType": "list",
        "label": "TV channels",
        "tooltip": "Select how TV audio channels are rendered.",
        "options": ["stereo", "mono", "left", "right"],
        "visibleWhen": {"objectKind": "tv"},
    },
    "mediaEffect": {
        "valueType": "list",
        "label": "TV effect",
        "tooltip": "Select the active TV audio effect.",
        "options": list(EFFECT_OPTIONS),
        "visibleWhen": {"objectKind": "tv"},
    },
    "mediaEffectValue": {
        "valueType": "number",
        "label": "TV effect amount",
        "tooltip": "Amount for the selected TV effect.",
        "range": {"min": 0, "max": 100, "step": 0.1},
        "visibleWhen": {"objectKind": "tv"},
    },
    "facing": {
        "valueType": "number",
        "label": "TV facing",
        "tooltip": "Direction this TV faces, in degrees.",
        "range": {"min": 0, "max": 360, "step": 1},
        "visibleWhen": {"objectKind": "tv"},
    },
    "enabled": {
        "valueType": "boolean",
        "tooltip": "Whether this object is active for use and any attached looped sound. For TVs, use toggles this power state.",
    },
    "emitRange": {
        "valueType": "number",
        "label": "Sound range",
        "tooltip": "How many grid squares away this object's looped sound can be heard.",
        "range": {"min": 1, "max": 20, "step": 1},
    },
    "emitVolume": {
        "valueType": "number",
        "label": "Sound volume",
        "tooltip": "Volume for this object's looped sound.",
        "range": {"min": 0, "max": 100, "step": 1},
    },
    "emitSoundSpeed": {
        "valueType": "number",
        "label": "Sound speed",
        "tooltip": "Speed/pitch for this object's looped sound.",
        "range": {"min": 0, "max": 100, "step": 1},
    },
    "emitSoundTempo": {
        "valueType": "number",
        "label": "Sound tempo",
        "tooltip": "Tempo control for this object's looped sound.",
        "range": {"min": 0, "max": 100, "step": 1},
    },
    "emitInitialDelay": {
        "valueType": "number",
        "label": "Sound start delay",
        "tooltip": "Seconds before this object's looped sound starts.",
        "range": {"min": 0, "max": 300, "step": 0.1},
    },
    "emitLoopDelay": {
        "valueType": "number",
        "label": "Sound loop delay",
        "tooltip": "Seconds between loop repeats for this object's emitted sound.",
        "range": {"min": 0, "max": 300, "step": 0.1},
    },
    "emitEffect": {
        "valueType": "list",
        "label": "Sound effect",
        "tooltip": "Optional effect for this object's looped sound.",
        "options": list(EFFECT_OPTIONS),
    },
    "emitEffectValue": {
        "valueType": "number",
        "label": "Sound effect amount",
        "tooltip": "Amount for the selected looped-sound effect.",
        "range": {"min": 0, "max": 100, "step": 1},
    },
    "useSound": {
        "valueType": "text",
        "label": "Use sound",
        "tooltip": "Optional one-shot sound when this object is used.",
        "maxLength": 2048,
    },
    "emitSound": {
        "valueType": "text",
        "label": "Looped sound",
        "tooltip": "Optional looped item sound such as a fridge hum, fan, or appliance tone.",
        "maxLength": 2048,
    },
}
