"""Built-in service/station items for the default Chat Grid world."""

from __future__ import annotations

from dataclasses import dataclass
from copy import deepcopy
import uuid

from .item_catalog import get_item_definition
from .models import WorldItem


RADIO_STATION_PRESETS: tuple[dict[str, str], ...] = (
    {
        "title": "SoulFoodRadio",
        "streamUrl": "https://aaastreamer.devinecreations.net/s/soulfoodradio-media",
        "switchSound": "sounds/radio/station-switch/soulfoodradio.mp3",
    },
    {
        "title": "DivineCreations radio",
        "streamUrl": "https://aaastreamer.devinecreations.net/s/main-stream",
        "switchSound": "sounds/radio/station-switch/divinecreations-radio.mp3",
    },
    {
        "title": "Chris Mix Radio",
        "streamUrl": "http://s23.myradiostream.com:9372/;",
        "switchSound": "sounds/radio/station-switch/soulfoodradio.mp3",
    },
    {
        "title": "StreamMadness - The Plague",
        "streamUrl": "http://streammadness.com:8000/;",
        "switchSound": "sounds/radio/station-switch/acb-media-1.mp3",
    },
    {
        "title": "BBC Radio 1",
        "streamUrl": "http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio1_mf_p",
        "switchSound": "sounds/radio/station-switch/acb-media-2.mp3",
    },
    {
        "title": "NPR Program Stream",
        "streamUrl": "https://npr-ice.streamguys1.com/live.mp3",
        "switchSound": "sounds/radio/station-switch/acb-media-3.mp3",
    },
    {
        "title": "Classical KUSC",
        "streamUrl": "https://kusc-ice.streamguys1.com/kusc-128-mp3",
        "switchSound": "sounds/radio/station-switch/acb-media-4.mp3",
    },
    {
        "title": "Jazz24",
        "streamUrl": "https://live.wostreaming.net/direct/ppm-jazz24mp3-ibc3",
        "switchSound": "sounds/radio/station-switch/acb-media-5.mp3",
    },
    {
        "title": "ACB Media 1",
        "streamUrl": "https://streaming.live365.com/a11911",
        "switchSound": "sounds/radio/station-switch/acb-media-1.mp3",
    },
    {
        "title": "ACB Media 2",
        "streamUrl": "https://streaming.live365.com/a27778",
        "switchSound": "sounds/radio/station-switch/acb-media-2.mp3",
    },
    {
        "title": "ACB Media 3",
        "streamUrl": "https://streaming.live365.com/a17972",
        "switchSound": "sounds/radio/station-switch/acb-media-3.mp3",
    },
    {
        "title": "ACB Media 4",
        "streamUrl": "https://streaming.live365.com/a89697",
        "switchSound": "sounds/radio/station-switch/acb-media-4.mp3",
    },
    {
        "title": "ACB Media 5",
        "streamUrl": "https://streaming.live365.com/a46090",
        "switchSound": "sounds/radio/station-switch/acb-media-5.mp3",
    },
    {
        "title": "ACB Media 6",
        "streamUrl": "https://streaming.live365.com/a36240",
        "switchSound": "sounds/radio/station-switch/acb-media-6.mp3",
    },
    {
        "title": "ACB Media 7",
        "streamUrl": "https://streaming.live365.com/a95398",
        "switchSound": "sounds/radio/station-switch/acb-media-7.mp3",
    },
    {
        "title": "ACB Media 8",
        "streamUrl": "https://streaming.live365.com/a18975",
        "switchSound": "sounds/radio/station-switch/acb-media-8.mp3",
    },
    {
        "title": "ACB Media 9",
        "streamUrl": "https://streaming.live365.com/a44175",
        "switchSound": "sounds/radio/station-switch/acb-media-9.mp3",
    },
    {
        "title": "ACB Media 10",
        "streamUrl": "https://streaming.live365.com/a85327",
        "switchSound": "sounds/radio/station-switch/acb-media-10.mp3",
    },
)

RAYWONDER_STUDIO_MUSIC_PRESETS: tuple[dict[str, str], ...] = (
    {
        "title": "SoulFoodRadio",
        "streamUrl": "https://aaastreamer.devinecreations.net/s/soulfoodradio-media",
        "switchSound": "sounds/radio/station-switch/soulfoodradio.mp3",
    },
    {
        "title": "DivineCreations radio",
        "streamUrl": "https://aaastreamer.devinecreations.net/s/main-stream",
        "switchSound": "sounds/radio/station-switch/divinecreations-radio.mp3",
    },
)

RAYWONDER_RELAXATION_PRESETS: tuple[dict[str, str], ...] = (
    {
        "title": "TappedIn 30 minute relaxation",
        "streamUrl": "sounds/radio/relaxation/tappedin-30min-relaxation.mp3",
        "switchSound": "sounds/radio/station-switch/soulfoodradio.mp3",
    },
    {
        "title": "TappedIn chirping birds",
        "streamUrl": "sounds/radio/relaxation/tappedin-chirping-birds.mp3",
        "switchSound": "sounds/radio/station-switch/divinecreations-radio.mp3",
    },
    {
        "title": "Steve G. Jones spiritual meditation",
        "streamUrl": "sounds/radio/relaxation/steve-g-jones-spiritual-meditation-module1.mp3",
        "switchSound": "sounds/radio/station-switch/acb-media-1.mp3",
    },
)

RAYWONDER_HOUSE_RADIO_PRESETS: tuple[dict[str, str], ...] = (
    *RADIO_STATION_PRESETS,
    *RAYWONDER_RELAXATION_PRESETS,
)

TELEPORT_START_SOUND = "sounds/teleport_departure_whoosh.ogg"
TELEPORT_LOOP_SOUND = "sounds/teleport_pad_loop.ogg"
PORTAL_LOOP_SOUND = "sounds/portal_spatial_loop.ogg"
HOUSE_THRESHOLD_LOOP_SOUND = "sounds/house_threshold_loop.ogg"
DOOR_LOOP_SOUND = "sounds/door_soft_loop.ogg"
FRIDGE_HUM_LOOP_SOUND = "sounds/house/fridge_hum_loop.ogg"

TELEPORT_PORTAL_AUDIO_PARAMS: dict[str, str | int] = {
    "useSound": TELEPORT_START_SOUND,
    "emitSound": TELEPORT_LOOP_SOUND,
    "emitRange": 12,
    "emitVolume": 48,
}

DEFAULT_OPEN_PORTAL_PARAMS: dict[str, str | int] = {
    "doorState": "unlocked",
    "portalDestinationMode": "static",
    "portalLocationPool": "",
    "portalState": "open",
    "portalOpenSeconds": 0,
    "portalClosedSeconds": 0,
}

RANDOM_PUBLIC_PORTAL_PARAMS: dict[str, str | int] = {
    "doorState": "unlocked",
    "portalDestinationMode": "random",
    "portalLocationPool": "city,forest,town,arcade,offices,houses",
    "portalState": "open",
    "portalOpenSeconds": 0,
    "portalClosedSeconds": 0,
}

DOOR_AUDIO_PARAMS: dict[str, str | int] = {
    "useSound": "sounds/teleport_start.ogg",
    "emitSound": DOOR_LOOP_SOUND,
    "emitRange": 7,
    "emitVolume": 32,
}

HOUSE_AUDIO_PARAMS: dict[str, str | int] = {
    "useSound": "sounds/teleport_start.ogg",
    "emitSound": HOUSE_THRESHOLD_LOOP_SOUND,
    "emitRange": 10,
    "emitVolume": 42,
}

DEFAULT_BILLBOARD_PARAMS: dict[str, str | int | bool] = {
    "enabled": True,
    "billboardMode": "interactive",
    "itemVisibility": "visible",
    "voiceName": "Clawdia",
    "rotationSeconds": 12,
    "emitRange": 14,
}


def furniture_params(
    *,
    kind: str,
    material: str = "wood",
    style: str = "warm home",
    supports_objects: bool = True,
    surface_slots: int = 0,
    seating_capacity: int = 0,
    posture_mode: str = "none",
    surface_note: str = "",
) -> dict[str, str | int | bool]:
    """Return complete seed params for one furniture item."""

    return {
        "furnitureKind": kind,
        "material": material,
        "style": style,
        "condition": "good",
        "supportsObjects": supports_objects,
        "surfaceSlots": surface_slots,
        "seatingCapacity": seating_capacity,
        "postureMode": posture_mode,
        "surfaceNote": surface_note,
    }


def house_object_params(
    *,
    kind: str,
    placement: str,
    material: str = "mixed",
    fragility: str = "normal",
    repair_cost: int = 8,
    purchase_cost: int = 14,
    replacement_hint: str = "A similar everyday replacement would work.",
    giftable: bool = True,
    description: str = "A small household object.",
    surface_id: str = "",
    surface_title: str = "",
    **extra: object,
) -> dict[str, object]:
    """Return complete seed params for one household object."""

    params: dict[str, object] = {
        "objectKind": kind,
        "placement": placement,
        "material": material,
        "fragility": fragility,
        "condition": "intact",
        "repairCost": repair_cost,
        "purchaseCost": purchase_cost,
        "replacementHint": replacement_hint,
        "giftable": giftable,
        "description": description,
        "surfaceId": surface_id,
        "surfaceTitle": surface_title,
    }
    params.update(extra)
    return params


DEPRECATED_BUILTIN_ITEM_IDS: tuple[str, ...] = (
    "seed-city-soulfoodradio",
    "seed-city-divinecreations-radio",
    "seed-city-acb-media-1",
    "seed-city-acb-media-2",
    "seed-city-acb-media-3",
    "seed-city-acb-media-4",
    "seed-city-acb-media-5",
    "seed-city-acb-media-6",
    "seed-city-acb-media-7",
    "seed-city-acb-media-8",
    "seed-city-acb-media-9",
    "seed-city-acb-media-10",
)


@dataclass(frozen=True)
class SeedItem:
    """One built-in item that should exist unless a matching user item exists."""

    type: str
    title: str
    location_id: str
    x: int
    y: int
    params: dict
    id: str = ""


BUILTIN_WORLD_ITEMS: tuple[SeedItem, ...] = (
    SeedItem(
        id="seed-city-chat-grid-radio",
        type="radio_station",
        title="Chat Grid Radio",
        location_id="city",
        x=5,
        y=8,
        params={
            "streamUrl": RADIO_STATION_PRESETS[0]["streamUrl"],
            "stationName": RADIO_STATION_PRESETS[0]["title"],
            "stationIndex": 0,
            "stationPresets": list(RADIO_STATION_PRESETS),
            "enabled": False,
            "mediaVolume": 50,
        },
    ),
    SeedItem(
        id="seed-city-aaastreamer",
        type="service_link",
        title="AAAStreamer",
        location_id="city",
        x=9,
        y=12,
        params={
            "serviceKind": "service",
            "url": "https://aaastreamer.devinecreations.net/",
            "description": "Streaming service hub for hosted stations and radio tools.",
            "launchMessage": "AAAStreamer service hub.",
        },
    ),
    SeedItem(
        id="seed-city-blindsoftware",
        type="service_link",
        title="blind.software",
        location_id="city",
        x=12,
        y=10,
        params={
            "serviceKind": "site",
            "url": "https://blind.software/",
            "description": "Catalog and community space for accessible software, downloads, media, repos, and account-tied help.",
        },
    ),
    SeedItem(
        id="seed-city-tappedin",
        type="service_link",
        title="tappedin.fm",
        location_id="city",
        x=14,
        y=10,
        params={
            "serviceKind": "site",
            "url": "https://tappedin.fm/",
            "description": "TappedIn home for shows, services, and project entry points.",
        },
    ),
    SeedItem(
        id="seed-city-portal-town",
        type="service_link",
        title="Town portal",
        location_id="city",
        x=19,
        y=20,
        params={
            "serviceKind": "portal",
            "targetLocation": "town",
            **DEFAULT_OPEN_PORTAL_PARAMS,
            "description": "A doorway from Main City to the Town location.",
            "launchMessage": "Entering Town.",
            **TELEPORT_PORTAL_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-city-portal-forest",
        type="service_link",
        title="Forest portal",
        location_id="city",
        x=20,
        y=18,
        params={
            "serviceKind": "portal",
            "targetLocation": "forest",
            **DEFAULT_OPEN_PORTAL_PARAMS,
            "description": "A doorway from Main City to the Forest location.",
            "launchMessage": "Entering Forest.",
            **TELEPORT_PORTAL_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-city-welcome-billboard",
        type="billboard",
        title="Main City billboard",
        location_id="city",
        x=20,
        y=17,
        params={
            **DEFAULT_BILLBOARD_PARAMS,
            "headline": "Welcome to Chat Grid",
            "body": "Walk the squares, hear nearby people and items, and use portals to visit the Town, Arcade, Offices, and Houses.",
            "announcementText": "Welcome to Chat Grid. The portals around you lead to the public rooms and games.",
            "voiceAssetUrl": "sounds/billboards/clawdia-welcome.mp3",
            "bannerText": "Town portal south-west|Arcade portal south-east|Offices portal north|Houses portal south",
        },
    ),
    SeedItem(
        id="seed-city-portal-arcade",
        type="service_link",
        title="Arcade portal",
        location_id="city",
        x=21,
        y=20,
        params={
            "serviceKind": "portal",
            "targetLocation": "arcade",
            **DEFAULT_OPEN_PORTAL_PARAMS,
            "description": "A doorway from Main City to the Arcade, where the game items live.",
            "launchMessage": "Entering Arcade.",
            **TELEPORT_PORTAL_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-city-portal-offices",
        type="service_link",
        title="Offices portal",
        location_id="city",
        x=20,
        y=19,
        params={
            "serviceKind": "portal",
            "targetLocation": "offices",
            **DEFAULT_OPEN_PORTAL_PARAMS,
            "description": "A doorway from Main City to the Offices location.",
            "launchMessage": "Entering Offices.",
            **TELEPORT_PORTAL_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-city-portal-houses",
        type="service_link",
        title="Houses portal",
        location_id="city",
        x=20,
        y=21,
        params={
            "serviceKind": "portal",
            "targetLocation": "houses",
            **DEFAULT_OPEN_PORTAL_PARAMS,
            "description": "A doorway from Main City to the Houses location.",
            "launchMessage": "Entering Houses.",
            **TELEPORT_PORTAL_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-city-portal-wildcard",
        type="service_link",
        title="Wildcard portal",
        location_id="city",
        x=20,
        y=22,
        params={
            "serviceKind": "portal",
            "targetLocation": "",
            **RANDOM_PUBLIC_PORTAL_PARAMS,
            "description": "A playful portal that chooses a public map destination at random.",
            "launchMessage": "The Wildcard portal spins up.",
            **TELEPORT_PORTAL_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-town-tcast",
        type="service_link",
        title="tCast",
        location_id="town",
        x=18,
        y=15,
        params={
            "serviceKind": "app",
            "url": "https://tappedin.fm/tcast-support/",
            "description": "Podcast and media player app support entry for tCast.",
        },
    ),
    SeedItem(
        id="seed-town-announcements-billboard",
        type="billboard",
        title="Town Square announcements",
        location_id="town",
        x=20,
        y=16,
        params={
            **DEFAULT_BILLBOARD_PARAMS,
            "billboardMode": "display_only",
            "headline": "Town Square",
            "body": "Apps, tools, and account services are gathered here.",
            "announcementText": "Town Square has tCast, Bema Media Player, Thrive Messenger, and the eCrypto Bank counter nearby.",
            "voiceAssetUrl": "sounds/billboards/clawdia-town.mp3",
            "bannerText": "tCast north-west|Bema north-east|Thrive south-west|eCrypto Bank center",
            "emitRange": 16,
        },
    ),
    SeedItem(
        id="seed-town-bema",
        type="service_link",
        title="Bema Media Player",
        location_id="town",
        x=21,
        y=15,
        params={
            "serviceKind": "app",
            "url": "https://bemamediaplayer.app/",
            "description": "Media player app entry for Bema Media Player.",
        },
    ),
    SeedItem(
        id="seed-town-thrive",
        type="service_link",
        title="Thrive Messenger",
        location_id="town",
        x=18,
        y=20,
        params={
            "serviceKind": "app",
            "description": "Messenger and agent backchannel space for approved conversations and coordination.",
        },
    ),
    SeedItem(
        id="seed-town-ecrypto-bank",
        type="ecrypto_bank",
        title="Crypto eCrypto Bank",
        location_id="town",
        x=20,
        y=18,
        params={
            "bankName": "Crypto eCrypto Bank",
            "serviceScope": "wallets_transfers",
            "targetLocation": "ecrypto_bank_lobby",
            "description": "Town Square service counter for each user's eCrypto wallet and related account activity.",
            "accessNote": "Wallet, balance, transfer, deposit, withdrawal, and account-specific eCrypto actions can be connected here as those services are wired in.",
            "emitSound": "sounds/ambience/ecrypto_bank_lobby.ogg?v=20260714-ecrypto-bank",
            "emitRange": 10,
            "emitVolume": 42,
        },
    ),
    SeedItem(
        id="seed-town-pocket-ecrypto-wallet",
        type="ecrypto_wallet",
        title="Pocket eCrypto wallet",
        location_id="town",
        x=19,
        y=18,
        params={
            "walletName": "Pocket eCrypto wallet",
            "networkMode": "test",
            "chain": "ecrypto-test",
            "walletLabel": "starter wallet",
            "custodyMode": "carried",
            "description": "A starter portable wallet marker. Pick it up to carry it with you.",
        },
    ),
    SeedItem(
        id="seed-city-ecrypto-bank",
        type="ecrypto_bank",
        title="Main City eCrypto Bank",
        location_id="city",
        x=7,
        y=24,
        params={
            "bankName": "Main City eCrypto Bank",
            "serviceScope": "wallets_transfers",
            "targetLocation": "ecrypto_bank_lobby",
            "description": "A fixed Main City bank branch for eCrypto wallet and transfer work.",
            "accessNote": "Banks are stationary service counters. Carry a wallet with you, then visit a branch for account actions.",
            "emitSound": "sounds/ambience/ecrypto_bank_lobby.ogg?v=20260714-ecrypto-bank",
            "emitRange": 10,
            "emitVolume": 42,
        },
    ),
    SeedItem(
        id="seed-forest-ecrypto-bank",
        type="ecrypto_bank",
        title="Forest Trail eCrypto Bank",
        location_id="forest",
        x=25,
        y=11,
        params={
            "bankName": "Forest Trail eCrypto Bank",
            "serviceScope": "wallets",
            "targetLocation": "ecrypto_bank_lobby",
            "description": "A small fixed branch tucked along the forest trail for wallet checks.",
            "accessNote": "This bank branch stays in the Forest; portable wallets can be carried between locations.",
            "emitSound": "sounds/ambience/ecrypto_bank_lobby.ogg?v=20260714-ecrypto-bank",
            "emitRange": 9,
            "emitVolume": 36,
        },
    ),
    SeedItem(
        id="seed-offices-ecrypto-bank",
        type="ecrypto_bank",
        title="Office District eCrypto Bank",
        location_id="offices",
        x=13,
        y=27,
        params={
            "bankName": "Office District eCrypto Bank",
            "serviceScope": "full_service",
            "targetLocation": "ecrypto_bank_lobby",
            "description": "A fixed office-district branch for account, wallet, deposit, withdrawal, and transfer tasks.",
            "accessNote": "Use this stationary counter for account work; keep wallet items on your person when traveling.",
            "emitSound": "sounds/ambience/ecrypto_bank_lobby.ogg?v=20260714-ecrypto-bank",
            "emitRange": 10,
            "emitVolume": 44,
        },
    ),
    SeedItem(
        id="seed-arcade-ecrypto-bank",
        type="ecrypto_bank",
        title="Arcade Prize eCrypto Bank",
        location_id="arcade",
        x=32,
        y=14,
        params={
            "bankName": "Arcade Prize eCrypto Bank",
            "serviceScope": "wallets_transfers",
            "targetLocation": "ecrypto_bank_lobby",
            "description": "A fixed arcade-side branch for wallet checks and test-chain prize transfers.",
            "accessNote": "This is a navigable in-world bank branch, not a carryable wallet.",
            "emitSound": "sounds/ambience/ecrypto_bank_lobby.ogg?v=20260714-ecrypto-bank",
            "emitRange": 8,
            "emitVolume": 38,
        },
    ),
    SeedItem(
        id="seed-houses-ecrypto-bank",
        type="ecrypto_bank",
        title="Neighborhood eCrypto Bank",
        location_id="houses",
        x=9,
        y=30,
        params={
            "bankName": "Neighborhood eCrypto Bank",
            "serviceScope": "deposits_withdrawals",
            "targetLocation": "ecrypto_bank_lobby",
            "description": "A fixed neighborhood bank branch near the house grid.",
            "accessNote": "Wallets can travel with users; bank branches stay on the map.",
            "emitSound": "sounds/ambience/ecrypto_bank_lobby.ogg?v=20260714-ecrypto-bank",
            "emitRange": 10,
            "emitVolume": 40,
        },
    ),
    SeedItem(
        id="seed-ecrypto-bank-lobby-teller",
        type="ecrypto_bank",
        title="eCrypto teller counter",
        location_id="ecrypto_bank_lobby",
        x=20,
        y=20,
        params={
            "bankName": "eCrypto teller counter",
            "serviceScope": "full_service",
            "targetLocation": "",
            "description": "Interior bank counter for account status, wallet links, deposits, withdrawals, and transfers.",
            "accessNote": "Use /ecrypto balance, wallets, connect, faucet, and transfer while inside the bank. Real-chain sends stay disabled until an approved provider/signature flow exists.",
            "emitSound": "sounds/ambience/ecrypto_bank_lobby.ogg?v=20260714-ecrypto-bank",
            "emitRange": 10,
            "emitVolume": 34,
        },
    ),
    SeedItem(
        id="seed-ecrypto-bank-lobby-atm",
        type="ecrypto_bank",
        title="eCrypto ATM",
        location_id="ecrypto_bank_lobby",
        x=23,
        y=21,
        params={
            "bankName": "eCrypto ATM",
            "serviceScope": "wallets_transfers",
            "targetLocation": "",
            "description": "A self-service bank terminal for quick balance, wallet, and test-chain transfer work.",
            "accessNote": "Use primary action for a quick account readout or /ecrypto commands for exact transaction actions.",
            "emitSound": "sounds/ambience/ecrypto_bank_lobby.ogg?v=20260714-ecrypto-bank",
            "emitRange": 8,
            "emitVolume": 30,
        },
    ),
    SeedItem(
        id="seed-ecrypto-bank-lobby-exit",
        type="service_link",
        title="Bank lobby exit",
        location_id="ecrypto_bank_lobby",
        x=20,
        y=24,
        params={
            "serviceKind": "portal",
            "targetLocation": "town",
            "description": "Exit back to Town Square.",
            "doorState": "unlocked",
            "portalDestinationMode": "static",
            "portalState": "open",
            "portalOpenSeconds": 0,
            "portalClosedSeconds": 0,
        },
    ),
    SeedItem(
        id="seed-town-park-bench",
        type="furniture",
        title="Town park bench",
        location_id="town",
        x=17,
        y=18,
        params=furniture_params(
            kind="bench",
            material="wood",
            style="outdoor park bench",
            supports_objects=False,
            seating_capacity=3,
            posture_mode="sit",
            surface_note="An outdoor bench for sitting in Town Square.",
        ),
    ),
    SeedItem(
        id="seed-town-fountain-edge",
        type="furniture",
        title="Fountain edge",
        location_id="town",
        x=20,
        y=19,
        params=furniture_params(
            kind="bench",
            material="stone",
            style="outdoor fountain ledge",
            supports_objects=False,
            seating_capacity=4,
            posture_mode="sit",
            surface_note="A stone ledge around the Town Square fountain.",
        ),
    ),
    SeedItem(
        id="seed-town-planter",
        type="furniture",
        title="Town planter",
        location_id="town",
        x=22,
        y=18,
        params=furniture_params(
            kind="plant_stand",
            material="stone",
            style="outdoor garden planter",
            surface_slots=3,
            surface_note="An outdoor planter that belongs beside the Town Square path.",
        ),
    ),
    SeedItem(
        id="seed-town-planter-flowers",
        type="house_object",
        title="Planter flowers",
        location_id="town",
        x=22,
        y=18,
        params=house_object_params(
            kind="plant",
            placement="furniture",
            material="plant",
            fragility="delicate",
            repair_cost=6,
            purchase_cost=18,
            replacement_hint="Outdoor garden flowers belong in the Town planter.",
            description="A bright set of outdoor flowers in the Town planter.",
            surface_id="seed-town-planter",
            surface_title="Town planter",
        ),
    ),
    SeedItem(
        id="seed-town-portal-city",
        type="service_link",
        title="Main City portal",
        location_id="town",
        x=18,
        y=18,
        params={
            "serviceKind": "portal",
            "targetLocation": "city",
            **DEFAULT_OPEN_PORTAL_PARAMS,
            "description": "A return doorway to Main City.",
            "launchMessage": "Returning to Main City.",
            **TELEPORT_PORTAL_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-town-cafe-entrance",
        type="service_link",
        title="Town Square Café entrance",
        location_id="town",
        x=24,
        y=18,
        params={
            "serviceKind": "portal",
            "targetLocation": "town_cafe",
            **DEFAULT_OPEN_PORTAL_PARAMS,
            "description": "A public café with tables, chairs, local ambience, and a live World Cup score board.",
            "launchMessage": "Entering the Town Square Café.",
            **DOOR_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-town-cafe-exit",
        type="service_link",
        title="Café exit to Town Square",
        location_id="town_cafe",
        x=20,
        y=24,
        params={
            "serviceKind": "portal",
            "targetLocation": "town",
            **DEFAULT_OPEN_PORTAL_PARAMS,
            "description": "The café door back to Town Square.",
            "launchMessage": "Returning to Town Square.",
            **DOOR_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-town-cafe-ambience",
        type="widget",
        title="Café room ambience",
        location_id="town_cafe",
        x=20,
        y=20,
        params={
            "enabled": True,
            "directional": False,
            "emitRange": 20,
            "emitVolume": 38,
            "emitSound": "sounds/ambience/town_cafe.ogg?v=20260715-world-cup-cafe",
            "ambienceScope": "location",
            "ambienceName": "Café conversation and soft kitchen clatter",
            "ambiencePriority": 90,
        },
    ),
    SeedItem(
        id="seed-town-cafe-counter",
        type="furniture",
        title="Café service counter",
        location_id="town_cafe",
        x=20,
        y=17,
        params=furniture_params(
            kind="counter",
            material="wood",
            style="accessible café service counter",
            surface_slots=6,
            surface_note="A wide service counter with a lowered accessible section.",
        ),
    ),
    SeedItem(
        id="seed-town-cafe-table-west",
        type="furniture",
        title="West café table",
        location_id="town_cafe",
        x=17,
        y=20,
        params=furniture_params(
            kind="table",
            material="wood",
            style="round café table with clear approach space",
            surface_slots=4,
            surface_note="A round table with open space for chairs and mobility devices.",
        ),
    ),
    SeedItem(
        id="seed-town-cafe-table-east",
        type="furniture",
        title="East café table",
        location_id="town_cafe",
        x=23,
        y=20,
        params=furniture_params(
            kind="table",
            material="wood",
            style="round café table with clear approach space",
            surface_slots=4,
            surface_note="A round table with open space for chairs and mobility devices.",
        ),
    ),
    SeedItem(
        id="seed-town-cafe-chair-west-a",
        type="furniture",
        title="West table chair one",
        location_id="town_cafe",
        x=16,
        y=20,
        params=furniture_params(kind="chair", style="café chair", supports_objects=False, seating_capacity=1, posture_mode="sit"),
    ),
    SeedItem(
        id="seed-town-cafe-chair-west-b",
        type="furniture",
        title="West table chair two",
        location_id="town_cafe",
        x=18,
        y=20,
        params=furniture_params(kind="chair", style="café chair", supports_objects=False, seating_capacity=1, posture_mode="sit"),
    ),
    SeedItem(
        id="seed-town-cafe-chair-east-a",
        type="furniture",
        title="East table chair one",
        location_id="town_cafe",
        x=22,
        y=20,
        params=furniture_params(kind="chair", style="café chair", supports_objects=False, seating_capacity=1, posture_mode="sit"),
    ),
    SeedItem(
        id="seed-town-cafe-chair-east-b",
        type="furniture",
        title="East table chair two",
        location_id="town_cafe",
        x=24,
        y=20,
        params=furniture_params(kind="chair", style="café chair", supports_objects=False, seating_capacity=1, posture_mode="sit"),
    ),
    SeedItem(
        id="seed-town-cafe-world-cup-tv",
        type="house_object",
        title="FIFA World Cup café TV",
        location_id="town_cafe",
        x=25,
        y=17,
        params=house_object_params(
            kind="tv",
            placement="wall",
            material="plastic",
            fragility="fragile",
            repair_cost=120,
            purchase_cost=500,
            giftable=False,
            replacement_hint="A wall-mounted accessible smart television.",
            description="A corner TV showing official FIFA World Cup live score and match-clock information. Use the adjacent board for the accessible live readout.",
            enabled=True,
            stationName="FIFA World Cup 2026 live scores",
            nowPlaying="Checking the official FIFA live feed.",
            tvChannelMode="live",
            linkedMediaGroup="town-cafe-world-cup",
            mediaVolume=35,
        ),
    ),
    SeedItem(
        id="seed-town-cafe-world-cup-board",
        type="billboard",
        title="FIFA World Cup live board",
        location_id="town_cafe",
        x=25,
        y=18,
        params={
            **DEFAULT_BILLBOARD_PARAMS,
            "billboardMode": "interactive",
            "headline": "FIFA World Cup 2026 live",
            "body": "Checking FIFA's official live score feed.",
            "url": "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/match-schedule-fixtures-results-teams-stadiums",
            "announcementText": "Welcome to the World Cup café. The accessible live score board is updating from FIFA.",
            "bannerText": "Official FIFA live scores|Match clock|Fixtures and results",
            "voiceName": "Clawdia",
            "voiceAssetUrl": "sounds/billboards/clawdia-town.mp3",
            "rotationSeconds": 10,
            "emitRange": 12,
        },
    ),
    SeedItem(
        id="seed-forest-camp-bench",
        type="furniture",
        title="Forest camp bench",
        location_id="forest",
        x=12,
        y=27,
        params=furniture_params(
            kind="bench",
            material="wood",
            style="outdoor forest camp bench",
            supports_objects=False,
            seating_capacity=3,
            posture_mode="sit",
            surface_note="An outdoor bench beside the forest path.",
        ),
    ),
    SeedItem(
        id="seed-forest-picnic-table",
        type="furniture",
        title="Forest picnic table",
        location_id="forest",
        x=13,
        y=28,
        params=furniture_params(
            kind="table",
            material="wood",
            style="outdoor picnic table",
            surface_slots=6,
            seating_capacity=4,
            posture_mode="sit",
            surface_note="A picnic table that belongs outdoors in the forest clearing.",
        ),
    ),
    SeedItem(
        id="seed-forest-trail-sign",
        type="house_object",
        title="Forest trail sign",
        location_id="forest",
        x=12,
        y=29,
        params=house_object_params(
            kind="sign",
            placement="fixture",
            material="wood",
            fragility="sturdy",
            repair_cost=10,
            purchase_cost=25,
            replacement_hint="An outdoor trail sign belongs beside the forest path.",
            giftable=False,
            description="An outdoor wooden trail sign for the forest path.",
        ),
    ),
    SeedItem(
        id="seed-forest-portal-city",
        type="service_link",
        title="Main City portal",
        location_id="forest",
        x=12,
        y=28,
        params={
            "serviceKind": "portal",
            "targetLocation": "city",
            **DEFAULT_OPEN_PORTAL_PARAMS,
            "description": "A return doorway to Main City.",
            "launchMessage": "Returning to Main City.",
            **TELEPORT_PORTAL_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-offices-voicelink",
        type="service_link",
        title="VoiceLink",
        location_id="offices",
        x=8,
        y=28,
        params={
            "serviceKind": "app",
            "description": "Voice room and communication app work area.",
        },
    ),
    SeedItem(
        id="seed-offices-projects-billboard",
        type="billboard",
        title="Office project board",
        location_id="offices",
        x=9,
        y=29,
        params={
            **DEFAULT_BILLBOARD_PARAMS,
            "headline": "Project offices",
            "body": "VoiceLink, OpenLink, OpenClaw, Clawdia, and FlexPBX work areas are grouped here.",
            "announcementText": "Project offices. VoiceLink, OpenLink, OpenClaw, Clawdia, and FlexPBX are close by.",
            "voiceAssetUrl": "sounds/billboards/clawdia-offices.mp3",
            "bannerText": "VoiceLink west|OpenLink east|OpenClaw south-west|FlexPBX south-east",
        },
    ),
    SeedItem(
        id="seed-offices-openlink",
        type="service_link",
        title="OpenLink",
        location_id="offices",
        x=10,
        y=28,
        params={
            "serviceKind": "tool",
            "description": "Remote support and control tool work area.",
        },
    ),
    SeedItem(
        id="seed-offices-openclaw",
        type="service_link",
        title="OpenClaw and Clawdia",
        location_id="offices",
        x=8,
        y=31,
        params={
            "serviceKind": "service",
            "description": "Agent coordination, memory, repair, and creative work area.",
        },
    ),
    SeedItem(
        id="seed-offices-flexpbx",
        type="service_link",
        title="FlexPBX",
        location_id="offices",
        x=10,
        y=31,
        params={
            "serviceKind": "service",
            "description": "Hosted PBX and call-flow service area.",
        },
    ),
    SeedItem(
        id="seed-offices-conference-table",
        type="furniture",
        title="Conference table",
        location_id="offices",
        x=9,
        y=30,
        params=furniture_params(
            kind="table",
            material="wood",
            style="office conference table",
            surface_slots=10,
            seating_capacity=6,
            posture_mode="sit",
            surface_note="A meeting table for project notes, laptops, and call plans.",
        ),
    ),
    SeedItem(
        id="seed-offices-task-chair",
        type="furniture",
        title="Office task chair",
        location_id="offices",
        x=8,
        y=30,
        params=furniture_params(
            kind="chair",
            material="fabric",
            style="office task chair",
            supports_objects=False,
            seating_capacity=1,
            posture_mode="sit",
            surface_note="A rolling office chair for focused work.",
        ),
    ),
    SeedItem(
        id="seed-offices-project-notebook",
        type="house_object",
        title="Project notebook",
        location_id="offices",
        x=9,
        y=30,
        params=house_object_params(
            kind="notebook",
            placement="table",
            material="paper",
            fragility="normal",
            repair_cost=3,
            purchase_cost=8,
            replacement_hint="A fresh notebook belongs on the office conference table.",
            description="A notebook for project notes and next steps.",
            surface_id="seed-offices-conference-table",
            surface_title="Conference table",
        ),
    ),
    SeedItem(
        id="seed-offices-desk-lamp",
        type="house_object",
        title="Office desk lamp",
        location_id="offices",
        x=9,
        y=30,
        params=house_object_params(
            kind="lamp",
            placement="table",
            material="metal",
            fragility="normal",
            repair_cost=12,
            purchase_cost=30,
            replacement_hint="A small office lamp belongs on a desk or conference table.",
            description="A focused desk lamp for the office table.",
            surface_id="seed-offices-conference-table",
            surface_title="Conference table",
        ),
    ),
    SeedItem(
        id="seed-offices-portal-city",
        type="service_link",
        title="Main City portal",
        location_id="offices",
        x=8,
        y=32,
        params={
            "serviceKind": "portal",
            "targetLocation": "city",
            **DEFAULT_OPEN_PORTAL_PARAMS,
            "description": "A return doorway to Main City.",
            "launchMessage": "Returning to Main City.",
            **TELEPORT_PORTAL_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-houses-raywonder-front-door",
        type="service_link",
        title="Raywonder House front door",
        location_id="houses",
        x=28,
        y=12,
        params={
            "serviceKind": "house",
            "url": "https://raywonderis.me/",
            "targetLocation": "raywonder_house_entry",
            "doorState": "unlocked",
            "accessAlarmItemId": "seed-raywonder-entry-house-alarm",
            "description": "A full Raywonder house with rooms you can enter through interior doors.",
            "launchMessage": "Opening the Raywonder House front door.",
            **HOUSE_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-houses-neighborhood-teleport-pad",
        type="service_link",
        title="Neighborhood teleport pad",
        location_id="houses",
        x=30,
        y=12,
        params={
            "serviceKind": "portal",
            "targetLocation": "city",
            **DEFAULT_OPEN_PORTAL_PARAMS,
            "description": "A teleport pad near the house row for quick travel back to Main City.",
            "launchMessage": "Teleporting back to Main City.",
            **TELEPORT_PORTAL_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-houses-front-porch-bench",
        type="furniture",
        title="Front porch bench",
        location_id="houses",
        x=29,
        y=12,
        params=furniture_params(
            kind="bench",
            material="wood",
            style="outdoor porch bench",
            supports_objects=False,
            seating_capacity=2,
            posture_mode="sit",
            surface_note="A porch bench by the Raywonder front door.",
        ),
    ),
    SeedItem(
        id="seed-houses-mailbox",
        type="house_object",
        title="Raywonder mailbox",
        location_id="houses",
        x=27,
        y=12,
        params=house_object_params(
            kind="mailbox",
            placement="fixture",
            material="metal",
            fragility="sturdy",
            repair_cost=18,
            purchase_cost=45,
            replacement_hint="An outdoor mailbox belongs beside the house row.",
            giftable=False,
            description="An outdoor mailbox for the Raywonder house.",
        ),
    ),
    SeedItem(
        id="seed-houses-portal-city",
        type="service_link",
        title="Main City portal",
        location_id="houses",
        x=30,
        y=14,
        params={
            "serviceKind": "portal",
            "targetLocation": "city",
            **DEFAULT_OPEN_PORTAL_PARAMS,
            "description": "A return doorway to Main City.",
            "launchMessage": "Returning to Main City.",
            **TELEPORT_PORTAL_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-raywonder-entry-door-houses",
        type="service_link",
        title="Front door to Houses",
        location_id="raywonder_house_entry",
        x=20,
        y=18,
        params={
            "serviceKind": "door",
            "targetLocation": "houses",
            "doorState": "unlocked",
            "description": "The front door back out to the Houses neighborhood.",
            "launchMessage": "Stepping back outside to Houses.",
            **DOOR_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-raywonder-entry-door-living-room",
        type="service_link",
        title="Living room door",
        location_id="raywonder_house_entry",
        x=18,
        y=20,
        params={
            "serviceKind": "door",
            "targetLocation": "raywonder_house_living_room",
            "doorState": "unlocked",
            "description": "An unlocked interior door into the Raywonder living room.",
            "launchMessage": "Entering the living room.",
            **DOOR_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-raywonder-entry-house-alarm",
        type="house_alarm",
        title="Raywonder alarm panel",
        location_id="houses",
        x=28,
        y=12,
        params={
            "alarmName": "Raywonder house alarm",
            "houseName": "Raywonder House",
            "ownerName": "Dom",
            "alarmMode": "entry_guard",
            "armedState": "armed_home",
            "codeMode": "off",
            "guestCode": "",
            "disarmCode": "",
            "duressCode": "",
            "codeHint": "",
            "authorizedNames": "Dom, Dominique, Clawdia",
            "authorizedUsernames": "dominique, clawdia_grid",
            "entryPrompt": "Please wait at the door. Dom or Clawdia can allow or deny entry.",
            "alertPrompt": "Raywonder house alarm. Someone is at the front entry.",
            "allowPrompt": "Access allowed. Welcome into the Raywonder house.",
            "denyPrompt": "Access denied. Please wait outside.",
            "notificationMode": "in_grid",
            "description": (
                "A voice-enabled panel for checking visitors before they enter."
            ),
        },
    ),
    SeedItem(
        id="seed-raywonder-entry-house-keeper",
        type="house_keeper",
        title="Raywonder house keeper",
        location_id="raywonder_house_entry",
        x=19,
        y=20,
        params={
            "keeperName": "Raywonder house keeper",
            "houseName": "Raywonder House",
            "repairMode": "auto_repair",
            "targetKinds": "radio, object",
            "authorizedNames": "",
            "voicePrompt": "I can check radios and small house things when someone asks.",
            "description": (
                "A small opt-in helper agent for in-world house repairs."
            ),
        },
    ),
    SeedItem(
        id="seed-raywonder-entry-door-studio",
        type="service_link",
        title="Studio door",
        location_id="raywonder_house_entry",
        x=22,
        y=20,
        params={
            "serviceKind": "door",
            "targetLocation": "raywonder_house_studio",
            "doorState": "locked",
            "description": (
                "A private studio door. If someone is inside, knock and wait "
                "to be allowed in."
            ),
            "launchMessage": "",
            **DOOR_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-raywonder-entry-studio-music-bleed",
        type="radio_station",
        title="Music under the studio door",
        location_id="raywonder_house_entry",
        x=22,
        y=20,
        params={
            "streamUrl": RAYWONDER_STUDIO_MUSIC_PRESETS[0]["streamUrl"],
            "stationName": RAYWONDER_STUDIO_MUSIC_PRESETS[0]["title"],
            "stationIndex": 0,
            "stationPresets": list(RAYWONDER_HOUSE_RADIO_PRESETS),
            "stationSwitchSound": RAYWONDER_STUDIO_MUSIC_PRESETS[0]["switchSound"],
            "enabled": True,
            "mediaVolume": 16,
            "mediaEffect": "low_pass",
            "mediaEffectValue": 68,
            "itemVisibility": "quiet",
            "linkedMediaGroup": "raywonder-house-radios",
            "speakerRole": "mid",
            "emitRange": 7,
        },
    ),
    SeedItem(
        id="seed-raywonder-entry-door-kitchen",
        type="service_link",
        title="Kitchen door",
        location_id="raywonder_house_entry",
        x=20,
        y=22,
        params={
            "serviceKind": "door",
            "targetLocation": "raywonder_house_kitchen",
            "doorState": "unlocked",
            "description": "An unlocked door into the kitchen.",
            "launchMessage": "Entering the kitchen.",
            **DOOR_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-raywonder-entry-door-bedroom",
        type="service_link",
        title="Bedroom door",
        location_id="raywonder_house_entry",
        x=20,
        y=24,
        params={
            "serviceKind": "door",
            "targetLocation": "raywonder_house_bedroom",
            "doorState": "locked",
            "requiredKeyId": "raywonder-bedroom-key",
            "keyLocationHint": "The bedroom key might be on the doorknob, in the entry hall, or with Clawdia.",
            "description": "A private bedroom door. It is currently locked.",
            **DOOR_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-raywonder-entry-bedroom-key",
        type="house_object",
        title="Bedroom key",
        location_id="raywonder_house_entry",
        x=20,
        y=24,
        params={
            "objectKind": "keys",
            "material": "metal",
            "fragility": "sturdy",
            "condition": "intact",
            "ownerName": "Dom",
            "keyId": "raywonder-bedroom-key",
            "keyFor": "the Raywonder bedroom door",
            "repairCost": 0,
            "purchaseCost": 0,
            "replacementHint": "If it goes missing, check the entry hall and the doorknob first.",
            "giftable": False,
            "description": "A small bedroom key resting where someone might have left it.",
        },
    ),
    SeedItem(
        id="seed-raywonder-entry-door-relaxation-room",
        type="service_link",
        title="Relaxation room door",
        location_id="raywonder_house_entry",
        x=21,
        y=24,
        params={
            "serviceKind": "room",
            "targetLocation": "raywonder_house_relaxation_room",
            "doorState": "unlocked",
            "description": "An unlocked door into a calm room with ocean sounds and relaxation radio.",
            "launchMessage": "Entering the relaxation room.",
            **DOOR_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-raywonder-living-door-entry",
        type="service_link",
        title="Door to entry hall",
        location_id="raywonder_house_living_room",
        x=18,
        y=20,
        params={
            "serviceKind": "door",
            "targetLocation": "raywonder_house_entry",
            "doorState": "unlocked",
            "description": "A return door to the Raywonder house entry hall.",
            "launchMessage": "Returning to the entry hall.",
            **DOOR_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-raywonder-living-room-radio",
        type="radio_station",
        title="Living room radio",
        location_id="raywonder_house_living_room",
        x=19,
        y=20,
        params={
            "streamUrl": RAYWONDER_STUDIO_MUSIC_PRESETS[0]["streamUrl"],
            "stationName": RAYWONDER_STUDIO_MUSIC_PRESETS[0]["title"],
            "stationIndex": 0,
            "stationPresets": list(RAYWONDER_HOUSE_RADIO_PRESETS),
            "stationSwitchSound": RAYWONDER_STUDIO_MUSIC_PRESETS[0]["switchSound"],
            "enabled": True,
            "mediaVolume": 24,
            "mediaEffect": "low_pass",
            "mediaEffectValue": 18,
            "linkedMediaGroup": "raywonder-house-radios",
            "speakerRole": "primary",
            "emitRange": 10,
        },
    ),
    SeedItem(
        id="seed-raywonder-living-room-couch",
        type="furniture",
        title="Living room couch",
        location_id="raywonder_house_living_room",
        x=18,
        y=21,
        params=furniture_params(
            kind="couch",
            material="fabric",
            style="warm living room",
            supports_objects=False,
            seating_capacity=4,
            posture_mode="sit",
            surface_note="A comfortable couch for sitting and listening in the living room.",
        ),
    ),
    SeedItem(
        id="seed-raywonder-living-room-coffee-table",
        type="furniture",
        title="Coffee table",
        location_id="raywonder_house_living_room",
        x=19,
        y=21,
        params=furniture_params(
            kind="table",
            material="wood",
            style="low coffee table",
            surface_slots=5,
            surface_note="A low table for mugs, remotes, and snacks.",
        ),
    ),
    SeedItem(
        id="seed-raywonder-living-room-radio-remote",
        type="house_object",
        title="Universal radio remote",
        location_id="raywonder_house_living_room",
        x=19,
        y=21,
        params=house_object_params(
            kind="remote",
            placement="table",
            material="plastic",
            fragility="normal",
            repair_cost=12,
            purchase_cost=35,
            replacement_hint="A programmable universal radio remote belongs with the house radios.",
            description="A programmable radio remote. Use tunes the nearest room radio; secondary use syncs all house radios to that station.",
            surface_id="seed-raywonder-living-room-coffee-table",
            surface_title="Coffee table",
            surfaceOrder=1,
            remoteControlLinkedRadios=True,
        ),
    ),
    SeedItem(
        id="seed-raywonder-living-room-tv",
        type="house_object",
        title="Living room wall TV",
        location_id="raywonder_house_living_room",
        x=20,
        y=20,
        params=house_object_params(
            kind="tv",
            placement="wall",
            material="mixed",
            fragility="normal",
            repair_cost=70,
            purchase_cost=300,
            replacement_hint="A wall-mounted TV belongs inside the living room, not outside.",
            giftable=False,
            description="A living room TV mounted on the wall with spatial room audio.",
            streamUrl=RADIO_STATION_PRESETS[0]["streamUrl"],
            stationName=RADIO_STATION_PRESETS[0]["title"],
            stationIndex=0,
            stationPresets=list(RADIO_STATION_PRESETS[:2]),
            linkedMediaGroup="raywonder-house-tv",
            tvChannelMode="live_and_on_demand",
            tvLibrarySources=[
                {
                    "key": "audio-described-movies",
                    "title": "Audio-described movies",
                    "kind": "movies",
                    "path": "/home/dom/apps/media/AudioDescribedContent/Movies",
                    "mode": "on_demand",
                },
                {
                    "key": "audio-described-tv",
                    "title": "Audio-described TV shows",
                    "kind": "shows",
                    "path": "/home/dom/apps/media/AudioDescribedContent/TV",
                    "mode": "live_and_on_demand",
                },
                {
                    "key": "misc-video",
                    "title": "Miscellaneous videos",
                    "kind": "misc",
                    "path": "/home/dom/apps/media/VIDEO",
                    "mode": "on_demand",
                },
            ],
            tvProviderSources=[
                {
                    "key": "raywonder-jellyfin",
                    "title": "Raywonder Jellyfin",
                    "kind": "jellyfin",
                    "url": "https://media.raywonderis.me/",
                    "provider": "jellyfin",
                    "mode": "live_and_on_demand",
                },
                {
                    "key": "pluto-tv",
                    "title": "Pluto TV",
                    "kind": "online",
                    "url": "https://pluto.tv/",
                    "provider": "pluto",
                    "mode": "live_and_on_demand",
                },
            ],
            mediaVolume=42,
            mediaChannel="stereo",
            emitRange=12,
            facing=180,
            enabled=True,
        ),
    ),
    SeedItem(
        id="seed-raywonder-living-room-tv-remote",
        type="house_object",
        title="Universal TV remote",
        location_id="raywonder_house_living_room",
        x=19,
        y=21,
        params=house_object_params(
            kind="remote",
            placement="table",
            material="plastic",
            fragility="normal",
            repair_cost=12,
            purchase_cost=35,
            replacement_hint="A programmable universal TV remote belongs on the living-room table.",
            description="A universal TV remote. Use changes the nearest TV channel; remote arrow controls tune channels and adjust volume.",
            surface_id="seed-raywonder-living-room-coffee-table",
            surface_title="Coffee table",
            surfaceOrder=0,
            remoteControlLinkedTvs=True,
        ),
    ),
    SeedItem(
        id="seed-raywonder-living-room-floor-lamp",
        type="house_object",
        title="Living room floor lamp",
        location_id="raywonder_house_living_room",
        x=17,
        y=21,
        params=house_object_params(
            kind="lamp",
            placement="floor",
            material="metal",
            fragility="normal",
            repair_cost=12,
            purchase_cost=38,
            replacement_hint="A floor lamp belongs beside a living room couch or chair.",
            description="A standing lamp beside the couch.",
        ),
    ),
    SeedItem(
        id="seed-raywonder-living-room-plant",
        type="house_object",
        title="Living room plant",
        location_id="raywonder_house_living_room",
        x=17,
        y=20,
        params=house_object_params(
            kind="plant",
            placement="floor",
            material="plant",
            fragility="delicate",
            repair_cost=6,
            purchase_cost=22,
            replacement_hint="A small indoor plant fits by the living room window.",
            description="A leafy plant beside the living room window.",
        ),
    ),
    SeedItem(
        id="seed-raywonder-living-room-window",
        type="house_object",
        title="Living room window",
        location_id="raywonder_house_living_room",
        x=17,
        y=20,
        params={
            "objectKind": "window",
            "placement": "wall",
            "material": "glass",
            "fragility": "delicate",
            "condition": "intact",
            "windowState": "open",
            "repairCost": 45,
            "purchaseCost": 120,
            "replacementHint": "A matching window pane can be repaired or replaced.",
            "giftable": False,
            "description": "An outside-facing window near the living room couch.",
        },
    ),
    SeedItem(
        id="seed-raywonder-studio-door-entry",
        type="service_link",
        title="Door to entry hall",
        location_id="raywonder_house_studio",
        x=22,
        y=20,
        params={
            "serviceKind": "door",
            "targetLocation": "raywonder_house_entry",
            "doorState": "unlocked",
            "description": "A return door to the Raywonder house entry hall.",
            "launchMessage": "Returning to the entry hall.",
            **DOOR_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-raywonder-studio-boombox",
        type="radio_station",
        title="Studio boombox",
        location_id="raywonder_house_studio",
        x=24,
        y=20,
        params={
            "streamUrl": RAYWONDER_STUDIO_MUSIC_PRESETS[0]["streamUrl"],
            "stationName": RAYWONDER_STUDIO_MUSIC_PRESETS[0]["title"],
            "stationIndex": 0,
            "stationPresets": list(RAYWONDER_HOUSE_RADIO_PRESETS),
            "stationSwitchSound": RAYWONDER_STUDIO_MUSIC_PRESETS[0]["switchSound"],
            "enabled": True,
            "mediaVolume": 42,
            "mediaEffect": "reverb",
            "mediaEffectValue": 18,
            "linkedMediaGroup": "raywonder-house-radios",
            "speakerRole": "primary",
            "emitRange": 12,
        },
    ),
    SeedItem(
        id="seed-raywonder-studio-desk",
        type="furniture",
        title="Studio work desk",
        location_id="raywonder_house_studio",
        x=23,
        y=21,
        params=furniture_params(
            kind="desk",
            material="wood",
            style="studio workstation",
            surface_slots=6,
            seating_capacity=1,
            posture_mode="sit",
            surface_note="A sturdy desk for keyboards, mixers, notebooks, and audio tools.",
        ),
    ),
    SeedItem(
        id="seed-raywonder-studio-wall-shelf",
        type="furniture",
        title="Studio wall shelf",
        location_id="raywonder_house_studio",
        x=24,
        y=21,
        params=furniture_params(
            kind="shelf",
            material="wood",
            style="wall-mounted studio shelf",
            surface_slots=5,
            surface_note="A wall shelf for small gear, figures, and keepsakes.",
        ),
    ),
    SeedItem(
        id="seed-raywonder-studio-window",
        type="house_object",
        title="Studio window",
        location_id="raywonder_house_studio",
        x=25,
        y=20,
        params={
            "objectKind": "window",
            "placement": "wall",
            "material": "glass",
            "fragility": "delicate",
            "condition": "intact",
            "windowState": "closed",
            "repairCost": 45,
            "purchaseCost": 120,
            "replacementHint": "A studio window repair should preserve quiet isolation.",
            "giftable": False,
            "description": "A closed studio window that keeps outside noise out during recording.",
        },
    ),
    SeedItem(
        id="seed-raywonder-studio-chair",
        type="furniture",
        title="Studio chair",
        location_id="raywonder_house_studio",
        x=23,
        y=22,
        params=furniture_params(
            kind="chair",
            material="fabric",
            style="studio desk chair",
            supports_objects=False,
            seating_capacity=1,
            posture_mode="sit",
            surface_note="A studio chair tucked near the work desk.",
        ),
    ),
    SeedItem(
        id="seed-raywonder-studio-notebook",
        type="house_object",
        title="Studio notebook",
        location_id="raywonder_house_studio",
        x=23,
        y=21,
        params=house_object_params(
            kind="notebook",
            placement="table",
            material="paper",
            repair_cost=4,
            purchase_cost=10,
            replacement_hint="A studio notebook belongs on the work desk.",
            description="A notebook for lyrics, app notes, and audio ideas.",
            surface_id="seed-raywonder-studio-desk",
            surface_title="Studio work desk",
        ),
    ),
    SeedItem(
        id="seed-raywonder-studio-monitor-speaker",
        type="house_object",
        title="Studio monitor speaker",
        location_id="raywonder_house_studio",
        x=23,
        y=21,
        params=house_object_params(
            kind="speaker",
            placement="table",
            material="mixed",
            fragility="normal",
            repair_cost=28,
            purchase_cost=120,
            replacement_hint="A monitor speaker belongs on the studio desk or speaker stand.",
            description="A compact monitor speaker on the studio desk.",
            surface_id="seed-raywonder-studio-desk",
            surface_title="Studio work desk",
        ),
    ),
    SeedItem(
        id="seed-raywonder-kitchen-door-entry",
        type="service_link",
        title="Door to entry hall",
        location_id="raywonder_house_kitchen",
        x=20,
        y=23,
        params={
            "serviceKind": "door",
            "targetLocation": "raywonder_house_entry",
            "doorState": "unlocked",
            "description": "A return door to the Raywonder house entry hall.",
            "launchMessage": "Returning to the entry hall.",
            **DOOR_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-raywonder-kitchen-counter-radio",
        type="radio_station",
        title="Kitchen counter radio",
        location_id="raywonder_house_kitchen",
        x=21,
        y=23,
        params={
            "streamUrl": RAYWONDER_STUDIO_MUSIC_PRESETS[1]["streamUrl"],
            "stationName": RAYWONDER_STUDIO_MUSIC_PRESETS[1]["title"],
            "stationIndex": 1,
            "stationPresets": list(RAYWONDER_HOUSE_RADIO_PRESETS),
            "stationSwitchSound": RAYWONDER_STUDIO_MUSIC_PRESETS[1]["switchSound"],
            "enabled": True,
            "mediaVolume": 20,
            "mediaEffect": "off",
            "mediaEffectValue": 50,
            "linkedMediaGroup": "raywonder-house-radios",
            "speakerRole": "mid",
            "emitRange": 9,
        },
    ),
    SeedItem(
        id="seed-raywonder-kitchen-fridge",
        type="house_object",
        title="Kitchen fridge",
        location_id="raywonder_house_kitchen",
        x=22,
        y=23,
        params={
            "objectKind": "fridge",
            "placement": "appliance",
            "material": "metal",
            "fragility": "sturdy",
            "condition": "intact",
            "repairCost": 85,
            "purchaseCost": 450,
            "replacementHint": "A working refrigerator belongs against the kitchen wall.",
            "giftable": False,
            "description": "A refrigerator with a low kitchen hum.",
            "enabled": True,
            "emitSound": FRIDGE_HUM_LOOP_SOUND,
            "emitRange": 5,
            "emitVolume": 38,
            "emitEffect": "low_pass",
            "emitEffectValue": 28,
        },
    ),
    SeedItem(
        id="seed-raywonder-kitchen-sink",
        type="house_object",
        title="Kitchen sink",
        location_id="raywonder_house_kitchen",
        x=21,
        y=24,
        params={
            "objectKind": "sink",
            "placement": "fixture",
            "material": "metal",
            "fragility": "sturdy",
            "condition": "intact",
            "repairCost": 55,
            "purchaseCost": 160,
            "replacementHint": "A sink repair should keep the counter and plumbing aligned.",
            "giftable": False,
            "description": "A kitchen sink set into the counter.",
        },
    ),
    SeedItem(
        id="seed-raywonder-kitchen-stove",
        type="house_object",
        title="Kitchen stove",
        location_id="raywonder_house_kitchen",
        x=22,
        y=24,
        params={
            "objectKind": "stove",
            "placement": "appliance",
            "material": "metal",
            "fragility": "sturdy",
            "condition": "intact",
            "repairCost": 90,
            "purchaseCost": 420,
            "replacementHint": "A safe stove or range belongs in this kitchen spot.",
            "giftable": False,
            "description": "A stove for kitchen ambience and everyday room realism.",
        },
    ),
    SeedItem(
        id="seed-raywonder-kitchen-microwave",
        type="house_object",
        title="Kitchen microwave",
        location_id="raywonder_house_kitchen",
        x=21,
        y=23,
        params=house_object_params(
            kind="microwave",
            placement="counter",
            material="metal",
            fragility="normal",
            repair_cost=35,
            purchase_cost=90,
            replacement_hint="A microwave belongs on the kitchen counter or appliance shelf.",
            giftable=False,
            description="A microwave sitting on the kitchen counter.",
            surface_id="seed-raywonder-kitchen-counter",
            surface_title="Kitchen counter",
        ),
    ),
    SeedItem(
        id="seed-raywonder-kitchen-mug",
        type="house_object",
        title="Kitchen mug",
        location_id="raywonder_house_kitchen",
        x=21,
        y=23,
        params=house_object_params(
            kind="mug",
            placement="counter",
            material="ceramic",
            fragility="fragile",
            repair_cost=5,
            purchase_cost=12,
            replacement_hint="A ceramic mug belongs on the kitchen counter or table.",
            description="A ceramic mug resting on the kitchen counter.",
            surface_id="seed-raywonder-kitchen-counter",
            surface_title="Kitchen counter",
        ),
    ),
    SeedItem(
        id="seed-raywonder-kitchen-counter",
        type="furniture",
        title="Kitchen counter",
        location_id="raywonder_house_kitchen",
        x=21,
        y=23,
        params=furniture_params(
            kind="counter",
            material="wood",
            style="fixed kitchen counter",
            surface_slots=8,
            surface_note="A counter surface for mugs, plates, radios, and small kitchen items.",
        ),
    ),
    SeedItem(
        id="seed-raywonder-kitchen-window",
        type="house_object",
        title="Kitchen window",
        location_id="raywonder_house_kitchen",
        x=20,
        y=24,
        params={
            "objectKind": "window",
            "placement": "wall",
            "material": "glass",
            "fragility": "delicate",
            "condition": "intact",
            "windowState": "open",
            "repairCost": 45,
            "purchaseCost": 120,
            "replacementHint": "A kitchen window should open cleanly for outside air and sounds.",
            "giftable": False,
            "description": "An open kitchen window that lets outdoor ambience carry in.",
        },
    ),
    SeedItem(
        id="seed-raywonder-bedroom-door-entry",
        type="service_link",
        title="Door to entry hall",
        location_id="raywonder_house_bedroom",
        x=20,
        y=18,
        params={
            "serviceKind": "door",
            "targetLocation": "raywonder_house_entry",
            "doorState": "unlocked",
            "description": "A return door to the Raywonder house entry hall.",
            "launchMessage": "Returning to the entry hall.",
            **DOOR_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-raywonder-bedroom-bedside-radio",
        type="radio_station",
        title="Bedside relaxation radio",
        location_id="raywonder_house_bedroom",
        x=21,
        y=18,
        params={
            "streamUrl": RAYWONDER_RELAXATION_PRESETS[0]["streamUrl"],
            "stationName": RAYWONDER_RELAXATION_PRESETS[0]["title"],
            "stationIndex": len(RADIO_STATION_PRESETS),
            "stationPresets": list(RAYWONDER_HOUSE_RADIO_PRESETS),
            "stationSwitchSound": RAYWONDER_RELAXATION_PRESETS[0]["switchSound"],
            "enabled": False,
            "mediaVolume": 18,
            "mediaEffect": "low_pass",
            "mediaEffectValue": 35,
            "linkedMediaGroup": "raywonder-house-radios",
            "speakerRole": "high",
            "emitRange": 8,
        },
    ),
    SeedItem(
        id="seed-raywonder-bedroom-bed",
        type="furniture",
        title="Bedroom bed",
        location_id="raywonder_house_bedroom",
        x=22,
        y=18,
        params=furniture_params(
            kind="bed",
            material="fabric",
            style="quiet bedroom",
            supports_objects=True,
            surface_slots=2,
            seating_capacity=1,
            posture_mode="lie",
            surface_note="A quiet bed area for the private room.",
        ),
    ),
    SeedItem(
        id="seed-raywonder-bedroom-rug",
        type="house_object",
        title="Bedroom rug",
        location_id="raywonder_house_bedroom",
        x=21,
        y=19,
        params={
            "objectKind": "rug",
            "placement": "floor",
            "material": "fabric",
            "fragility": "normal",
            "condition": "intact",
            "repairCost": 8,
            "purchaseCost": 45,
            "replacementHint": "A soft rug fits the bedroom floor.",
            "giftable": True,
            "description": "A soft rug that matches the bedroom carpet ambience.",
        },
    ),
    SeedItem(
        id="seed-raywonder-bedroom-nightstand",
        type="furniture",
        title="Bedroom nightstand",
        location_id="raywonder_house_bedroom",
        x=21,
        y=18,
        params=furniture_params(
            kind="nightstand",
            material="wood",
            style="bedside nightstand",
            surface_slots=3,
            surface_note="A bedside surface for a lamp, book, radio, or phone.",
        ),
    ),
    SeedItem(
        id="seed-raywonder-bedroom-lamp",
        type="house_object",
        title="Bedside lamp",
        location_id="raywonder_house_bedroom",
        x=21,
        y=18,
        params=house_object_params(
            kind="lamp",
            placement="table",
            material="mixed",
            fragility="normal",
            repair_cost=10,
            purchase_cost=28,
            replacement_hint="A bedside lamp belongs on the nightstand.",
            description="A soft bedside lamp on the nightstand.",
            surface_id="seed-raywonder-bedroom-nightstand",
            surface_title="Bedroom nightstand",
        ),
    ),
    SeedItem(
        id="seed-raywonder-bedroom-book",
        type="house_object",
        title="Bedside book",
        location_id="raywonder_house_bedroom",
        x=21,
        y=18,
        params=house_object_params(
            kind="book",
            placement="table",
            material="paper",
            repair_cost=3,
            purchase_cost=14,
            replacement_hint="A book belongs on the nightstand or shelf.",
            description="A bedside book resting on the nightstand.",
            surface_id="seed-raywonder-bedroom-nightstand",
            surface_title="Bedroom nightstand",
        ),
    ),
    SeedItem(
        id="seed-raywonder-bedroom-window",
        type="house_object",
        title="Bedroom window",
        location_id="raywonder_house_bedroom",
        x=20,
        y=19,
        params={
            "objectKind": "window",
            "placement": "wall",
            "material": "glass",
            "fragility": "delicate",
            "condition": "intact",
            "windowState": "closed",
            "repairCost": 45,
            "purchaseCost": 120,
            "replacementHint": "A private bedroom window should close securely.",
            "giftable": False,
            "description": "A closed private window that keeps the bedroom quiet.",
        },
    ),
    SeedItem(
        id="seed-raywonder-relaxation-door-entry",
        type="service_link",
        title="Door to entry hall",
        location_id="raywonder_house_relaxation_room",
        x=20,
        y=18,
        params={
            "serviceKind": "door",
            "targetLocation": "raywonder_house_entry",
            "doorState": "unlocked",
            "description": "A return door to the Raywonder house entry hall.",
            "launchMessage": "Returning to the entry hall.",
            **DOOR_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-raywonder-relaxation-ocean-radio",
        type="radio_station",
        title="Ocean relaxation radio",
        location_id="raywonder_house_relaxation_room",
        x=20,
        y=20,
        params={
            "streamUrl": RAYWONDER_RELAXATION_PRESETS[0]["streamUrl"],
            "stationName": RAYWONDER_RELAXATION_PRESETS[0]["title"],
            "stationIndex": len(RADIO_STATION_PRESETS),
            "stationPresets": list(RAYWONDER_HOUSE_RADIO_PRESETS),
            "stationSwitchSound": RAYWONDER_RELAXATION_PRESETS[0]["switchSound"],
            "enabled": True,
            "mediaVolume": 34,
            "mediaEffect": "reverb",
            "mediaEffectValue": 22,
            "linkedMediaGroup": "raywonder-house-radios",
            "speakerRole": "sub",
            "emitRange": 12,
        },
    ),
    SeedItem(
        id="seed-arcade-moonstep-runner",
        type="service_link",
        title="Moonstep Runner",
        location_id="arcade",
        x=20,
        y=18,
        params={
            "serviceKind": "game",
            "url": "https://blind.software/private/moonstep-28c93ae33fd0e29d/",
            "description": "Clawdia's moonlit browser runner with directional movement sounds, chorus mode, and generated music.",
            "launchMessage": "Moonstep Runner is ready to play.",
        },
    ),
    SeedItem(
        id="seed-arcade-moonstep-billboard",
        type="billboard",
        title="Arcade billboard",
        location_id="arcade",
        x=20,
        y=17,
        params={
            **DEFAULT_BILLBOARD_PARAMS,
            "headline": "Moonstep Runner",
            "body": "Gather on the Moonstep Runner square to launch it together.",
            "url": "https://blind.software/private/moonstep-28c93ae33fd0e29d/",
            "announcementText": "Moonstep Runner is active in the Arcade. Stand on the game square together to play as a group.",
            "voiceAssetUrl": "sounds/billboards/clawdia-arcade.mp3",
            "bannerText": "MIDI support|Binaural footsteps|Location ambience|Chorus mode",
            "emitRange": 18,
        },
    ),
    SeedItem(
        id="seed-arcade-audio-only-billboard",
        type="billboard",
        title="Arcade overhead speaker",
        location_id="arcade",
        x=24,
        y=18,
        params={
            **DEFAULT_BILLBOARD_PARAMS,
            "billboardMode": "audio_only",
            "itemVisibility": "hidden",
            "headline": "",
            "body": "",
            "announcementText": "Arcade speaker test. Farther away I get more roomy and wobbly. Closer in, I clean up.",
            "bannerText": "Old vinyl speaker wobble|Room echo test|Spatial announcement active",
            "rotationSeconds": 10,
            "emitRange": 20,
        },
    ),
    SeedItem(
        id="seed-arcade-future-games",
        type="service_link",
        title="Future games shelf",
        location_id="arcade",
        x=22,
        y=18,
        params={
            "serviceKind": "game",
            "description": "A placeholder shelf for future Chat Grid games and playful experiments.",
            "launchMessage": "Future games will appear here as they are added.",
        },
    ),
    SeedItem(
        id="seed-arcade-clawdia-toolkit",
        type="service_link",
        title="Clawdia's toolkit",
        location_id="arcade",
        x=20,
        y=21,
        params={
            "serviceKind": "tool",
            "description": "A shared bundle spot for useful Clawdia-made toys, helpers, sounds, and experiments other logged-in users can try.",
            "launchMessage": "Clawdia's shared toolkit is open for useful little experiments.",
        },
    ),
    SeedItem(
        id="seed-arcade-portal-city",
        type="service_link",
        title="Main City portal",
        location_id="arcade",
        x=20,
        y=20,
        params={
            "serviceKind": "portal",
            "targetLocation": "city",
            **DEFAULT_OPEN_PORTAL_PARAMS,
            "description": "A return doorway to Main City.",
            "launchMessage": "Returning to Main City.",
            **TELEPORT_PORTAL_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-houses-matthew-front-door",
        type="service_link",
        title="Matthew's front door",
        location_id="houses",
        x=24,
        y=12,
        params={
            "serviceKind": "house",
            "targetLocation": "matthew_house_entry",
            "doorState": "unlocked",
            "accessAlarmItemId": "seed-houses-matthew-alarm",
            "description": "Matthew's accessible home near the Raywonder house.",
            "launchMessage": "Opening Matthew's front door.",
            **HOUSE_AUDIO_PARAMS,
        },
    ),
    SeedItem(
        id="seed-houses-matthew-alarm",
        type="house_alarm",
        title="Matthew's alarm keypad",
        location_id="houses",
        x=24,
        y=12,
        params={
            "alarmName": "Matthew's house alarm",
            "houseName": "Matthew's House",
            "ownerName": "Matthew",
            "alarmMode": "entry_guard",
            "armedState": "armed_home",
            "codeMode": "off",
            "guestCode": "",
            "disarmCode": "",
            "duressCode": "",
            "codeHint": "Ask Matthew for access.",
            "authorizedNames": "Matthew, Matthew Whitaker, Dom, Dominique, Clawdia",
            "authorizedUsernames": "matthew-whitaker, dominique, clawdia_grid",
            "entryPrompt": "Please wait outside while Matthew or an authorized resident responds.",
            "alertPrompt": "Matthew's house alarm. Someone is at the front door.",
            "allowPrompt": "Access allowed. Welcome to Matthew's house.",
            "denyPrompt": "Access denied. Please wait outside.",
            "notificationMode": "in_grid",
            "description": "A working exterior alarm keypad guarding Matthew's front door.",
        },
    ),
    SeedItem(
        id="seed-houses-matthew-porch-bench",
        type="furniture",
        title="Matthew's porch bench",
        location_id="houses",
        x=25,
        y=12,
        params=furniture_params(
            kind="bench", material="wood", style="accessible front porch",
            supports_objects=False, seating_capacity=2, posture_mode="sit",
            surface_note="A bench beside Matthew's secured front door.",
        ),
    ),
    SeedItem(
        id="seed-matthew-entry-door-outside",
        type="service_link",
        title="Front door to Houses",
        location_id="matthew_house_entry",
        x=20,
        y=18,
        params={"serviceKind": "door", "targetLocation": "houses", "doorState": "unlocked", "description": "The front door back outside.", "launchMessage": "Stepping outside.", **DOOR_AUDIO_PARAMS},
    ),
    SeedItem(
        id="seed-matthew-entry-door-living",
        type="service_link",
        title="Living room door",
        location_id="matthew_house_entry",
        x=18,
        y=20,
        params={"serviceKind": "door", "targetLocation": "matthew_house_living_room", "doorState": "unlocked", "description": "An interior door to Matthew's living room.", "launchMessage": "Entering the living room.", **DOOR_AUDIO_PARAMS},
    ),
    SeedItem(
        id="seed-matthew-entry-door-music",
        type="service_link",
        title="Music room door",
        location_id="matthew_house_entry",
        x=22,
        y=20,
        params={"serviceKind": "door", "targetLocation": "matthew_house_music_room", "doorState": "unlocked", "description": "An interior door to Matthew's music room.", "launchMessage": "Entering the music room.", **DOOR_AUDIO_PARAMS},
    ),
    SeedItem(
        id="seed-matthew-living-door-entry",
        type="service_link",
        title="Door to entry hall",
        location_id="matthew_house_living_room",
        x=18,
        y=20,
        params={"serviceKind": "door", "targetLocation": "matthew_house_entry", "doorState": "unlocked", "description": "The return door to the entry hall.", "launchMessage": "Returning to the entry hall.", **DOOR_AUDIO_PARAMS},
    ),
    SeedItem(
        id="seed-matthew-living-radio",
        type="radio_station",
        title="Matthew's living room radio",
        location_id="matthew_house_living_room",
        x=19,
        y=20,
        params={
            "streamUrl": RADIO_STATION_PRESETS[7]["streamUrl"],
            "stationName": RADIO_STATION_PRESETS[7]["title"],
            "stationIndex": 7,
            "stationPresets": list(RADIO_STATION_PRESETS),
            "stationSwitchSound": RADIO_STATION_PRESETS[7]["switchSound"],
            "enabled": False,
            "mediaVolume": 30,
            "mediaEffect": "none",
            "mediaEffectValue": 0,
            "linkedMediaGroup": "matthew-house-radios",
            "speakerRole": "primary",
            "emitRange": 10,
        },
    ),
    SeedItem(
        id="seed-matthew-living-couch",
        type="furniture",
        title="Matthew's living room couch",
        location_id="matthew_house_living_room",
        x=18,
        y=21,
        params=furniture_params(kind="couch", material="fabric", style="comfortable listening room", supports_objects=False, seating_capacity=4, posture_mode="sit", surface_note="A couch for conversation and listening together."),
    ),
    SeedItem(
        id="seed-matthew-music-door-entry",
        type="service_link",
        title="Door to entry hall",
        location_id="matthew_house_music_room",
        x=22,
        y=20,
        params={"serviceKind": "door", "targetLocation": "matthew_house_entry", "doorState": "unlocked", "description": "The return door to the entry hall.", "launchMessage": "Returning to the entry hall.", **DOOR_AUDIO_PARAMS},
    ),
    SeedItem(
        id="seed-matthew-music-piano",
        type="piano",
        title="Matthew's piano",
        location_id="matthew_house_music_room",
        x=23,
        y=20,
        params={"description": "An accessible playable piano in Matthew's music room."},
    ),
    SeedItem(
        id="seed-matthew-music-radio",
        type="radio_station",
        title="Matthew's music room radio",
        location_id="matthew_house_music_room",
        x=24,
        y=20,
        params={
            "streamUrl": RADIO_STATION_PRESETS[7]["streamUrl"],
            "stationName": RADIO_STATION_PRESETS[7]["title"],
            "stationIndex": 7,
            "stationPresets": list(RADIO_STATION_PRESETS),
            "stationSwitchSound": RADIO_STATION_PRESETS[7]["switchSound"],
            "enabled": False,
            "mediaVolume": 36,
            "mediaEffect": "reverb",
            "mediaEffectValue": 12,
            "linkedMediaGroup": "matthew-house-radios",
            "speakerRole": "primary",
            "emitRange": 12,
        },
    ),
)

# Filename-reviewed defaults from Archive/fx/Ambiance. These are location-scoped
# controls rather than audible point sources; the generated files have a
# crossfaded seam and therefore loop from zero through their declared end.
LOCATION_AMBIENCE_DEFAULTS: tuple[tuple[str, str, str], ...] = (
    ("city", "amb-urbn-realistic-city-stree-bbbee213", "Urban: realistic city street"),
    ("forest", "amb-forst-natural-ambient-soun-50f65b96", "Forest: natural ambient sound"),
    ("town", "amb-park-ambience-of-a-outdoo-ba37fe64", "Park: outdoor ambience"),
    ("town_cafe", "amb-rest-create-background-cr-2e0dfff2", "Restaurant: café background"),
    ("arcade", "amb-sci-an-ambient-cosmic-so-dbe72782", "Science fiction: ambient cosmic sound"),
    ("offices", "amb-offc-seamless-quiet-offic-9342289f", "Office: seamless quiet office"),
    ("ecrypto_bank_lobby", "amb-offc-ambience-of-a-high-e-8cd5a665", "Office: high-end lobby"),
    ("houses", "amb-subn-late-spring-afternoo-c2bc153e", "Suburban: late spring afternoon"),
    ("raywonder_house_entry", "amb-room-basic-room-tone-with-27615d58", "Room: basic room tone"),
    ("matthew_house_entry", "amb-room-basic-room-tone-with-27615d58", "Room: basic room tone"),
    ("raywonder_house_living_room", "amb-home-a-quiet-apartment-li-0b41f25f", "Home: quiet apartment living room"),
    ("matthew_house_living_room", "amb-home-a-quiet-apartment-li-0b41f25f", "Home: quiet apartment living room"),
    ("raywonder_house_studio", "amb-offc-background-studio-am-9ef0c15f", "Office: background studio ambience"),
    ("matthew_house_music_room", "amb-offc-background-studio-am-9ef0c15f", "Office: background studio ambience"),
    ("raywonder_house_kitchen", "amb-rest-busy-kitchen-ambienc-2ad7c414", "Restaurant: busy kitchen ambience"),
    ("raywonder_house_bedroom", "amb-room-quiet-vintage-hotel-e66f04d7", "Room: quiet vintage bedroom"),
    ("raywonder_house_relaxation_room", "amb-sea-looping-ambient-soun-817274bf", "Sea: looping ambient sound"),
)

BUILTIN_WORLD_ITEMS += tuple(
    SeedItem(
        id=f"seed-location-ambience-{location_id}",
        type="widget",
        title=f"{location_id.replace('_', ' ').title()} ambience control",
        location_id=location_id,
        x=1,
        y=1,
        params={
            "enabled": True,
            "emitSound": f"sounds/ambience/fx/{sound_id}.ogg?v=20260716-fx-loops",
            "emitVolume": 50,
            "ambienceScope": "location",
            "ambienceName": label,
            "ambiencePriority": 100,
            "ambienceSoundId": sound_id,
            "ambienceLoopStartSeconds": 0.0,
        },
    )
    for location_id, sound_id, label in LOCATION_AMBIENCE_DEFAULTS
)


def _matching_seed_exists(items: dict[str, WorldItem], seed: SeedItem) -> bool:
    """Return true if this built-in seed is already represented."""

    if seed.id and seed.id in items:
        return True
    seed_title = seed.title.casefold()
    for item in items.values():
        if item.type != seed.type:
            continue
        if item.locationId != seed.location_id:
            continue
        if item.title.casefold() == seed_title:
            return True
    return False


def build_seed_item(seed: SeedItem, *, now_ms: int) -> WorldItem:
    """Create one WorldItem from seed metadata and catalog defaults."""

    definition = get_item_definition(seed.type)
    params = deepcopy(definition.default_params)
    params.update(deepcopy(seed.params))
    return WorldItem(
        id=seed.id or str(uuid.uuid4()),
        type=seed.type,
        title=seed.title,
        locationId=seed.location_id,
        x=seed.x,
        y=seed.y,
        createdBy="system",
        createdByName="system",
        updatedBy="system",
        updatedByName="system",
        createdAt=now_ms,
        updatedAt=now_ms,
        version=1,
        capabilities=list(definition.capabilities),
        useSound=definition.use_sound,
        emitSound=definition.emit_sound,
        params=params,
        carrierId=None,
    )


def ensure_builtin_items(items: dict[str, WorldItem], *, now_ms: int) -> list[WorldItem]:
    """Insert/update built-in service/station items and return changed items."""

    changed: list[WorldItem] = []
    for item_id in DEPRECATED_BUILTIN_ITEM_IDS:
        item = items.get(item_id)
        if item is not None and item.createdBy == "system":
            del items[item_id]
    for seed in BUILTIN_WORLD_ITEMS:
        existing = items.get(seed.id) if seed.id else None
        if existing is not None and existing.createdBy == "system":
            if (
                existing.type != seed.type
                or existing.locationId != seed.location_id
                or existing.x != seed.x
                or existing.y != seed.y
            ):
                replacement = build_seed_item(seed, now_ms=now_ms)
                replacement.createdAt = existing.createdAt
                replacement.version = existing.version + 1
                items[replacement.id] = replacement
                changed.append(replacement)
                continue
            updated = False
            preserve_existing_params = existing.updatedBy not in {"", "system", None}
            if existing.title != seed.title and not preserve_existing_params:
                existing.title = seed.title
                updated = True
            for key, value in seed.params.items():
                server_managed_tv_metadata = key in {"tvLibrarySources", "tvProviderSources"}
                if key not in existing.params:
                    existing.params[key] = deepcopy(value)
                    updated = True
                elif (
                    not preserve_existing_params or server_managed_tv_metadata
                ) and existing.params.get(key) != value:
                    existing.params[key] = deepcopy(value)
                    updated = True
            if updated:
                existing.updatedAt = now_ms
                existing.updatedBy = "system"
                existing.updatedByName = "system"
                existing.version += 1
                changed.append(existing)
            continue
        if _matching_seed_exists(items, seed):
            continue
        item = build_seed_item(seed, now_ms=now_ms)
        items[item.id] = item
        changed.append(item)
    return changed
