import type { CommandDescriptor } from './commandTypes';
import type { MainModeCommand } from './mainCommandRouter';

export type MainModeCommandAvailabilityContext = {
  voiceSendAllowed: boolean;
  mainHelpAvailable: boolean;
  hasAdminActions: boolean;
  itemTypeCount: number;
  visibleItemCount: number;
  userCount: number;
  hasDirectMessageTarget: boolean;
  locationCount: number;
  chatMessageCount: number;
  hasCarriedItem: boolean;
  hasCarriedRadioRemote: boolean;
  squareItemCount: number;
  usableItemCount: number;
  manageableItemCount: number;
  hasEditableItemTarget: boolean;
  hasInspectableItemTarget: boolean;
  hasFocusedUserTarget: boolean;
};

type MainModeCommandDescriptor = CommandDescriptor<MainModeCommand> & {
  isAvailable: (context: MainModeCommandAvailabilityContext) => boolean;
};

const MAIN_MODE_COMMANDS: MainModeCommandDescriptor[] = [
  {
    id: 'editNickname',
    label: 'Edit nickname',
    shortcut: 'N',
    tooltip: 'Edit your current nickname.',
    section: 'Users',
    isAvailable: () => true,
  },
  {
    id: 'openNotifications',
    label: 'Open notifications',
    shortcut: 'Shift+N',
    tooltip: 'Read, navigate, and mark your account notifications as read.',
    section: 'Users',
    isAvailable: () => true,
  },
  {
    id: 'toggleMute',
    label: 'Mute or unmute microphone',
    shortcut: 'M / 8 / Shift+8',
    tooltip: 'Toggle local microphone mute.',
    section: 'Audio',
    isAvailable: () => true,
  },
  {
    id: 'toggleOutputMode',
    label: 'Toggle stereo or mono output',
    shortcut: 'Shift+M / 7 / Shift+7',
    tooltip: 'Switch between stereo and mono output.',
    section: 'Audio',
    isAvailable: () => true,
  },
  {
    id: 'toggleLoopback',
    label: 'Toggle loopback monitor',
    shortcut: 'Shift+1',
    tooltip: 'Toggle local microphone loopback monitoring.',
    section: 'Audio',
    isAvailable: () => true,
  },
  {
    id: 'toggleVoiceLayer',
    label: 'Toggle voice layer',
    shortcut: '1 / 9 / Shift+9',
    tooltip: 'Enable or disable voice audio.',
    section: 'Audio',
    isAvailable: () => true,
  },
  {
    id: 'toggleItemLayer',
    label: 'Toggle item layer',
    shortcut: '2 / Shift+2',
    tooltip: 'Enable or disable item sounds.',
    section: 'Audio',
    isAvailable: () => true,
  },
  {
    id: 'toggleMediaLayer',
    label: 'Toggle media layer',
    shortcut: '3 / Shift+3',
    tooltip: 'Enable or disable media audio such as radio.',
    section: 'Audio',
    isAvailable: () => true,
  },
  {
    id: 'toggleWorldLayer',
    label: 'Toggle world layer',
    shortcut: '4 / Shift+4',
    tooltip: 'Enable or disable other world sounds.',
    section: 'Audio',
    isAvailable: () => true,
  },
  {
    id: 'cycleAnnouncementMode',
    label: 'Cycle TTS announcements',
    shortcut: '5 / Shift+5',
    tooltip: 'Switch between full announcements, alert sounds only, and required announcements only.',
    section: 'Audio',
    isAvailable: () => true,
  },
  {
    id: 'toggleItemBeacons',
    label: 'Toggle item beacons',
    shortcut: '6 / Shift+6',
    tooltip: 'Turn optional nearby item beacon pings on or off. Required item alerts remain active.',
    section: 'Audio',
    isAvailable: () => true,
  },
  {
    id: 'masterVolumeUp',
    label: 'Raise master volume',
    shortcut: '=',
    tooltip: 'Increase overall output volume.',
    section: 'Audio',
    isAvailable: () => true,
  },
  {
    id: 'masterVolumeDown',
    label: 'Lower master volume',
    shortcut: '-',
    tooltip: 'Decrease overall output volume.',
    section: 'Audio',
    isAvailable: () => true,
  },
  {
    id: 'openEffectSelect',
    label: 'Open effect select',
    shortcut: 'E',
    tooltip: 'Open the effects menu.',
    section: 'Audio',
    isAvailable: () => true,
  },
  {
    id: 'effectValueUp',
    label: 'Raise active effect value',
    shortcut: 'Shift+=',
    tooltip: 'Increase the selected effect amount.',
    section: 'Audio',
    isAvailable: () => true,
  },
  {
    id: 'effectValueDown',
    label: 'Lower active effect value',
    shortcut: 'Shift+-',
    tooltip: 'Decrease the selected effect amount.',
    section: 'Audio',
    isAvailable: () => true,
  },
  {
    id: 'speakCoordinates',
    label: 'Speak coordinates',
    shortcut: 'C',
    tooltip: 'Announce your current coordinates.',
    section: 'Navigation',
    isAvailable: () => true,
  },
  {
    id: 'speakLocation',
    label: 'Speak current location',
    shortcut: 'Y',
    tooltip: 'Announce the room or location you are currently in.',
    section: 'Navigation',
    isAvailable: () => true,
  },
  {
    id: 'openMicGainEdit',
    label: 'Set microphone gain',
    shortcut: 'V',
    tooltip: 'Open microphone gain editing.',
    section: 'Audio',
    isAvailable: (context) => context.voiceSendAllowed,
  },
  {
    id: 'calibrateMicrophone',
    label: 'Calibrate microphone',
    shortcut: 'Shift+V',
    tooltip: 'Run microphone calibration.',
    section: 'Audio',
    isAvailable: (context) => context.voiceSendAllowed,
  },
  {
    id: 'cycleFocusedItem',
    label: 'Cycle item focus',
    shortcut: 'Tab / Shift+Tab',
    tooltip: 'Cycle through carried items and items on your current square.',
    section: 'Items',
    isAvailable: (context) => context.hasCarriedItem || context.squareItemCount > 0,
  },
  {
    id: 'useItem',
    label: 'Use item',
    shortcut: 'Enter / Space',
    tooltip: 'Use the focused, carried, current doorway, or portal-style item on your square.',
    section: 'Items',
    isAvailable: (context) => context.hasCarriedItem || context.usableItemCount > 0,
  },
  {
    id: 'secondaryUseItem',
    label: 'Secondary item action',
    shortcut: 'Shift+J',
    tooltip: 'Run the secondary action for the focused, carried, or usable item on your current square.',
    section: 'Items',
    isAvailable: (context) => context.hasCarriedItem || context.usableItemCount > 0,
  },
  {
    id: 'radioRemoteStationPrevious',
    label: 'Radio remote previous station',
    shortcut: 'Shift+Space / Left / Comma / Ctrl+Comma',
    tooltip: 'Tune connected radios to the previous station while holding a radio remote.',
    section: 'Radio',
    isAvailable: (context) => context.hasCarriedRadioRemote,
  },
  {
    id: 'radioRemoteStationNext',
    label: 'Radio remote next station',
    shortcut: 'Space / Right / Period / Ctrl+Period',
    tooltip: 'Tune connected radios to the next station while holding a radio remote.',
    section: 'Radio',
    isAvailable: (context) => context.hasCarriedRadioRemote,
  },
  {
    id: 'radioRemoteVolumeUp',
    label: 'Radio remote volume up',
    shortcut: 'Up / Ctrl+Shift+Up / Ctrl+Shift+U',
    tooltip: 'Raise connected radio volume while holding a radio remote.',
    section: 'Radio',
    isAvailable: (context) => context.hasCarriedRadioRemote,
  },
  {
    id: 'radioRemoteVolumeDown',
    label: 'Radio remote volume down',
    shortcut: 'Down / Ctrl+Shift+Down / Ctrl+Shift+D',
    tooltip: 'Lower connected radio volume while holding a radio remote.',
    section: 'Radio',
    isAvailable: (context) => context.hasCarriedRadioRemote,
  },
  {
    id: 'castToDevice',
    label: 'Cast remote to device',
    shortcut: 'Shift+K',
    tooltip: 'Choose a nearby TV or radio and cast the local device stream through the carried universal remote.',
    section: 'Media',
    isAvailable: (context) => context.hasCarriedRadioRemote,
  },
  {
    id: 'openWorldPhone',
    label: 'Open world phone',
    tooltip: 'Open the carried in-world phone dialer and contacts.',
  },
  {
    id: 'openUserActionMenu',
    label: 'User action menu',
    shortcut: 'Shift+R',
    tooltip: 'Open contextual actions for the selected, focused, or nearest user.',
    section: 'Users',
    isAvailable: (context) => context.hasFocusedUserTarget,
  },
  {
    id: 'allowNearbyUser',
    label: 'Allow nearby user into house',
    shortcut: 'Shift+H',
    tooltip: 'Approve the focused or nearest visitor at your guarded house door without requiring an access code.',
    section: 'Users',
    isAvailable: (context) => context.hasFocusedUserTarget,
  },
  {
    id: 'interactItem',
    label: 'Object interaction',
    shortcut: 'Shift+Enter',
    tooltip: 'Interact with the focused object without picking it up: repair it or move it off its surface.',
    section: 'Items',
    isAvailable: (context) => context.squareItemCount > 0,
  },
  {
    id: 'pickupSurfaceItem',
    label: 'Pick up surface item',
    shortcut: 'J',
    tooltip: 'Pick up the focused grabbable item from a table, shelf, counter, or other surface.',
    section: 'Items',
    isAvailable: (context) => context.squareItemCount > 0,
  },
  {
    id: 'describeSurface',
    label: 'Describe surface contents',
    shortcut: 'Shift+J',
    tooltip: 'Announce what is on the focused table, shelf, counter, or the floor beneath you.',
    section: 'Items',
    isAvailable: (context) => context.squareItemCount > 0,
  },
  {
    id: 'speakUsers',
    label: 'Speak connected users',
    shortcut: 'U',
    tooltip: 'Announce your current room, connected-user count, and connected users.',
    section: 'Users',
    isAvailable: () => true,
  },
  {
    id: 'addItem',
    label: 'Add item',
    shortcut: 'A',
    tooltip: 'Open the add-item menu.',
    section: 'Items',
    isAvailable: (context) => context.itemTypeCount > 0,
  },
  {
    id: 'locateNearestItem',
    label: 'Locate nearest item',
    shortcut: 'I',
    tooltip: 'Announce the nearest visible item.',
    section: 'Items',
    isAvailable: (context) => context.visibleItemCount > 0,
  },
  {
    id: 'listItems',
    label: 'List items',
    shortcut: 'Shift+I',
    tooltip: 'Open the nearby item list and teleport with Enter.',
    section: 'Items',
    isAvailable: (context) => context.visibleItemCount > 0,
  },
  {
    id: 'pickupDropItem',
    label: 'Pick up or set down item',
    shortcut: 'D',
    tooltip: 'Pick up an item or movable surface; tabletop and shelf contents remain balanced while the surface moves.',
    section: 'Items',
    isAvailable: (context) => context.hasCarriedItem || context.squareItemCount > 0,
  },
  {
    id: 'pickupDropAttachedItems',
    label: 'Pick up or drop attached group',
    shortcut: 'Shift+D',
    tooltip: 'Move the selected item together with attached, surfaced, or linked parts such as a room with its door and included objects.',
    section: 'Items',
    isAvailable: (context) => context.hasCarriedItem || context.squareItemCount > 0,
  },
  {
    id: 'openItemManagement',
    label: 'Item management',
    shortcut: 'Z',
    tooltip: 'Open item management actions for items on your square.',
    section: 'Items',
    isAvailable: (context) => context.manageableItemCount > 0,
  },
  {
    id: 'editItem',
    label: 'Edit item properties',
    shortcut: 'O',
    tooltip: 'Edit the carried item or an item on your current square.',
    section: 'Items',
    isAvailable: (context) => context.hasEditableItemTarget,
  },
  {
    id: 'inspectItem',
    label: 'Inspect item properties',
    shortcut: 'Shift+O',
    tooltip: 'Inspect all properties for the carried item or an item on your current square.',
    section: 'Items',
    isAvailable: (context) => context.hasInspectableItemTarget,
  },
  {
    id: 'pingServer',
    label: 'Ping server',
    shortcut: 'P',
    tooltip: 'Measure round-trip latency to the server.',
    section: 'Network',
    isAvailable: () => true,
  },
  {
    id: 'locateNearestUser',
    label: 'Locate nearest user',
    shortcut: 'L',
    tooltip: 'Announce the nearest connected user.',
    section: 'Users',
    isAvailable: (context) => context.userCount > 0,
  },
  {
    id: 'listUsers',
    label: 'List users',
    shortcut: 'Shift+L',
    tooltip: 'Open the user list; Enter teleports and left or right adjust listen volume.',
    section: 'Users',
    isAvailable: (context) => context.userCount > 0,
  },
  {
    id: 'listLocations',
    label: 'Go to location',
    shortcut: 'G / Ctrl+G / Shift+G',
    tooltip: 'Open the location list; Enter travels to the selected place.',
    section: 'Navigation',
    isAvailable: (context) => context.locationCount > 0,
  },
  {
    id: 'openHelp',
    label: 'Open help',
    shortcut: '?',
    tooltip: 'Open the main help viewer.',
    section: 'Help',
    isAvailable: (context) => context.mainHelpAvailable,
  },
  {
    id: 'openChat',
    label: 'Open chat',
    shortcut: '/ / H',
    tooltip: 'Start typing a room chat message.',
    section: 'Chat',
    isAvailable: () => true,
  },
  {
    id: 'openDirectMessage',
    label: 'Direct message user',
    shortcut: 'Ctrl+M',
    tooltip: 'Start a private message to the selected or nearest user.',
    section: 'Chat',
    isAvailable: (context) => context.hasDirectMessageTarget,
  },
  {
    id: 'openAdminMenu',
    label: 'Open admin menu',
    shortcut: 'Shift+Z',
    tooltip: 'Open the admin actions menu when permitted.',
    section: 'Admin',
    isAvailable: (context) => context.hasAdminActions,
  },
  {
    id: 'chatPrev',
    label: 'Previous chat message',
    shortcut: ',',
    tooltip: 'Read the previous buffered chat message.',
    section: 'Chat',
    isAvailable: (context) => context.chatMessageCount > 0,
  },
  {
    id: 'chatNext',
    label: 'Next chat message',
    shortcut: '.',
    tooltip: 'Read the next buffered chat message.',
    section: 'Chat',
    isAvailable: (context) => context.chatMessageCount > 0,
  },
  {
    id: 'chatFirst',
    label: 'First chat message',
    shortcut: 'Shift+,',
    tooltip: 'Jump to the first buffered chat message.',
    section: 'Chat',
    isAvailable: (context) => context.chatMessageCount > 0,
  },
  {
    id: 'chatLast',
    label: 'Last chat message',
    shortcut: 'Shift+.',
    tooltip: 'Jump to the last buffered chat message.',
    section: 'Chat',
    isAvailable: (context) => context.chatMessageCount > 0,
  },
  {
    id: 'escape',
    label: 'Disconnect prompt',
    shortcut: 'Escape',
    tooltip: 'Press once for a disconnect prompt and again to disconnect.',
    section: 'System',
    isAvailable: () => true,
  },
];

export function getAvailableMainModeCommands(
  context: MainModeCommandAvailabilityContext,
): MainModeCommandDescriptor[] {
  return MAIN_MODE_COMMANDS.filter((command) => command.isAvailable(context));
}
